# Generated by Django 4.1.3 on 2022-11-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1)),
                ('icon', models.ImageField(default=None, upload_to='static/img/target_icon')),
                ('domain', models.CharField(max_length=300)),
                ('last_change', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCANNING', 'Scanning'), ('FINISHED', 'Finished'), ('WAITING', 'Waiting')], default='WAITING', max_length=9)),
                ('command', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
