# Generated by Django 4.0.5 on 2022-11-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='scan_mode',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
