---
- hosts: all
  become: true
  vars:
    reconftw_repo: "https://github.com/six2dez/reconftw.git"
    reconftw_dest: "/opt/reconftw"
    reconftw_branch_default: "main"
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 86400

    - name: Ensure git is installed (required to clone the repo)
      ansible.builtin.apt:
        name: git
        state: present

    - name: Clone reconFTW
      ansible.builtin.git:
        repo: "{{ reconftw_repo }}"
        dest: "{{ reconftw_dest }}"
        version: "{{ reconftw_branch | default(reconftw_branch_default) }}"
        update: yes

    - name: Install reconFTW dependencies and tools
      ansible.builtin.command: ./install.sh --verbose
      args:
        chdir: "{{ reconftw_dest }}"

    - name: Copy reconftw.cfg
      ansible.builtin.copy:
        src: files/reconftw.cfg
        dest: "{{ reconftw_dest }}/reconftw.cfg"
        owner: root
        group: root
        mode: "0644"
