// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companies.sql

package sqlcgen

import (
	"context"
)

const countCompanies = `-- name: CountCompanies :one
SELECT COUNT(*) FROM companies
`

func (q *Queries) CountCompanies(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCompanies)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (id, name, description, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?4)
RETURNING id, name, description, created_at, updated_at
`

type CreateCompanyParams struct {
	ID          string
	Name        string
	Description string
	Now         int64
}

// Plain INSERT (not UPSERT). ScansCreate-style handlers want a hard
// error on duplicate id; the UpsertCompany helper from Phase 1 stays
// available for ingestion paths.
func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, createCompany,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Now,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCompany = `-- name: DeleteCompany :exec
DELETE FROM companies WHERE id = ?
`

func (q *Queries) DeleteCompany(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCompany, id)
	return err
}

const getCompany = `-- name: GetCompany :one
SELECT id, name, description, created_at, updated_at FROM companies WHERE id = ? LIMIT 1
`

func (q *Queries) GetCompany(ctx context.Context, id string) (Company, error) {
	row := q.db.QueryRowContext(ctx, getCompany, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, name, description, created_at, updated_at FROM companies
ORDER BY name
LIMIT ? OFFSET ?
`

type ListCompaniesParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]Company, error) {
	rows, err := q.db.QueryContext(ctx, listCompanies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompaniesCursor = `-- name: ListCompaniesCursor :many
SELECT id, name, description, created_at, updated_at FROM companies
WHERE id < ?
ORDER BY id DESC
LIMIT ?
`

type ListCompaniesCursorParams struct {
	ID    string
	Limit int64
}

// Cursor-based pagination by id DESC. Caller passes the last_id from the
// previous page; for the first page, caller passes the ULID-max sentinel
// (26 'Z' chars, larger than any real Crockford-base32 ULID). D-16.
func (q *Queries) ListCompaniesCursor(ctx context.Context, arg ListCompaniesCursorParams) ([]Company, error) {
	rows, err := q.db.QueryContext(ctx, listCompaniesCursor, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE companies SET
    name        = ?1,
    description = ?2,
    updated_at  = ?3
WHERE id = ?4
RETURNING id, name, description, created_at, updated_at
`

type UpdateCompanyParams struct {
	Name        string
	Description string
	Now         int64
	ID          string
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, updateCompany,
		arg.Name,
		arg.Description,
		arg.Now,
		arg.ID,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCompany = `-- name: UpsertCompany :one

INSERT INTO companies (
    id, name, description, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4, ?4
)
ON CONFLICT(id) DO UPDATE SET
    name        = excluded.name,
    description = excluded.description,
    updated_at  = excluded.updated_at
RETURNING id, name, description, created_at, updated_at
`

type UpsertCompanyParams struct {
	ID          string
	Name        string
	Description string
	Now         int64
}

// Phase 1, Plan 05 -- companies query file.
//
// Caller supplies the ULID `id` (NewCompanyID in the domain layer); the
// SQL layer never generates IDs. All UPSERT/UPDATE queries return the
// row via RETURNING * so the caller does not re-fetch.
//
// Every query uses `?` or `@named` placeholders (T-Tampering-1 mitigation).
func (q *Queries) UpsertCompany(ctx context.Context, arg UpsertCompanyParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, upsertCompany,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Now,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
