// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: findings.sql

package sqlcgen

import (
	"context"
)

const attachFindingToTarget = `-- name: AttachFindingToTarget :exec
INSERT INTO target_finding(target_id, finding_id) VALUES (?, ?)
ON CONFLICT(target_id, finding_id) DO NOTHING
`

type AttachFindingToTargetParams struct {
	TargetID  string
	FindingID int64
}

func (q *Queries) AttachFindingToTarget(ctx context.Context, arg AttachFindingToTargetParams) error {
	_, err := q.db.ExecContext(ctx, attachFindingToTarget, arg.TargetID, arg.FindingID)
	return err
}

const getFinding = `-- name: GetFinding :one
SELECT id, template_signature, tool, host_id, port_id, url_id, path, severity, status, title, description, evidence, matched_at, cvss_score, tags_json, notes, raw_json, first_seen_at, last_seen_at, target_id FROM findings WHERE id = ? LIMIT 1
`

func (q *Queries) GetFinding(ctx context.Context, id int64) (Finding, error) {
	row := q.db.QueryRowContext(ctx, getFinding, id)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.TemplateSignature,
		&i.Tool,
		&i.HostID,
		&i.PortID,
		&i.URLID,
		&i.Path,
		&i.Severity,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.Evidence,
		&i.MatchedAt,
		&i.CVSSScore,
		&i.TagsJson,
		&i.Notes,
		&i.RawJson,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.TargetID,
	)
	return i, err
}

const listFindingsBySeverityForTarget = `-- name: ListFindingsBySeverityForTarget :many
SELECT f.id, f.template_signature, f.severity, f.status, f.title, f.matched_at
FROM target_finding tf
JOIN findings f ON f.id = tf.finding_id
WHERE tf.target_id = ?
  AND f.severity IN ('critical','high')
  AND f.status = 'open'
ORDER BY f.first_seen_at DESC
LIMIT ?
`

type ListFindingsBySeverityForTargetParams struct {
	TargetID string
	Limit    int64
}

type ListFindingsBySeverityForTargetRow struct {
	ID                int64
	TemplateSignature string
	Severity          string
	Status            string
	Title             string
	MatchedAt         string
}

func (q *Queries) ListFindingsBySeverityForTarget(ctx context.Context, arg ListFindingsBySeverityForTargetParams) ([]ListFindingsBySeverityForTargetRow, error) {
	rows, err := q.db.QueryContext(ctx, listFindingsBySeverityForTarget, arg.TargetID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFindingsBySeverityForTargetRow
	for rows.Next() {
		var i ListFindingsBySeverityForTargetRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateSignature,
			&i.Severity,
			&i.Status,
			&i.Title,
			&i.MatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsCursor = `-- name: ListFindingsCursor :many
SELECT f.id, f.template_signature, f.tool, f.host_id, f.port_id, f.url_id,
       f.path, f.severity, f.status, f.title, f.description, f.evidence,
       f.matched_at, f.cvss_score, f.tags_json, f.notes, f.raw_json,
       f.first_seen_at, f.last_seen_at, f.target_id
FROM findings f
LEFT JOIN target_finding tf ON tf.finding_id = f.id
WHERE (?1 = '' OR tf.target_id = ?1)
  AND (?2 = 0 OR f.host_id = ?2)
  AND (?3 = '' OR f.severity = ?3)
  AND (?4 = '' OR f.status = ?4)
  AND (?5 = 0 OR f.id < ?5)
ORDER BY f.id DESC
LIMIT ?6
`

type ListFindingsCursorParams struct {
	TargetID     interface{}
	HostIDFilter interface{}
	Severity     interface{}
	StatusFilter interface{}
	CursorLastID interface{}
	RowLimit     int64
}

// Plan 04-04 - cursor-paginated findings list for GET /api/v1/findings.
//
// Filter columns: target_id (via target_finding join), host_id, severity, status.
// Cursor: id < cursor_last_id (0 -> first page); findings.id is INTEGER
// auto-increment, so a single-column cursor on id DESC is sufficient and
// monotonic across concurrent UPSERTs (new rows always get a higher id).
// Tag filter deferred to Phase 6 (tags live in JSON column; no normalized
// finding_tag table in the v1 schema).
func (q *Queries) ListFindingsCursor(ctx context.Context, arg ListFindingsCursorParams) ([]Finding, error) {
	rows, err := q.db.QueryContext(ctx, listFindingsCursor,
		arg.TargetID,
		arg.HostIDFilter,
		arg.Severity,
		arg.StatusFilter,
		arg.CursorLastID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.TemplateSignature,
			&i.Tool,
			&i.HostID,
			&i.PortID,
			&i.URLID,
			&i.Path,
			&i.Severity,
			&i.Status,
			&i.Title,
			&i.Description,
			&i.Evidence,
			&i.MatchedAt,
			&i.CVSSScore,
			&i.TagsJson,
			&i.Notes,
			&i.RawJson,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.TargetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsForTarget = `-- name: ListFindingsForTarget :many
SELECT f.id, f.template_signature, f.tool, f.host_id, f.port_id, f.url_id, f.path, f.severity, f.status, f.title, f.description, f.evidence, f.matched_at, f.cvss_score, f.tags_json, f.notes, f.raw_json, f.first_seen_at, f.last_seen_at, f.target_id
FROM target_finding tf
JOIN findings f ON f.id = tf.finding_id
WHERE tf.target_id = ?
ORDER BY f.first_seen_at DESC
LIMIT ? OFFSET ?
`

type ListFindingsForTargetParams struct {
	TargetID string
	Limit    int64
	Offset   int64
}

func (q *Queries) ListFindingsForTarget(ctx context.Context, arg ListFindingsForTargetParams) ([]Finding, error) {
	rows, err := q.db.QueryContext(ctx, listFindingsForTarget, arg.TargetID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.TemplateSignature,
			&i.Tool,
			&i.HostID,
			&i.PortID,
			&i.URLID,
			&i.Path,
			&i.Severity,
			&i.Status,
			&i.Title,
			&i.Description,
			&i.Evidence,
			&i.MatchedAt,
			&i.CVSSScore,
			&i.TagsJson,
			&i.Notes,
			&i.RawJson,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.TargetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchFinding = `-- name: PatchFinding :one
UPDATE findings
SET status    = COALESCE(?1,    status),
    tags_json = COALESCE(?2, tags_json),
    notes     = COALESCE(?3,     notes)
WHERE id = ?4
RETURNING id, template_signature, tool, host_id, port_id, url_id, path, severity, status, title, description, evidence, matched_at, cvss_score, tags_json, notes, raw_json, first_seen_at, last_seen_at, target_id
`

type PatchFindingParams struct {
	NewStatus   *string
	NewTagsJson *string
	NewNotes    *string
	ID          int64
}

// Plan 04-04 - single-finding triage patch (status + tags_json + notes).
// COALESCE(sqlc.narg, col) keeps the column unchanged when the named
// nullable parameter is NULL. State-machine transition rules deferred
// to Phase 6 UX-02; this query accepts any value within the schema
// CHECK constraint on findings.status.
func (q *Queries) PatchFinding(ctx context.Context, arg PatchFindingParams) (Finding, error) {
	row := q.db.QueryRowContext(ctx, patchFinding,
		arg.NewStatus,
		arg.NewTagsJson,
		arg.NewNotes,
		arg.ID,
	)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.TemplateSignature,
		&i.Tool,
		&i.HostID,
		&i.PortID,
		&i.URLID,
		&i.Path,
		&i.Severity,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.Evidence,
		&i.MatchedAt,
		&i.CVSSScore,
		&i.TagsJson,
		&i.Notes,
		&i.RawJson,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.TargetID,
	)
	return i, err
}

const updateFindingStatus = `-- name: UpdateFindingStatus :exec
UPDATE findings SET
    status    = ?1,
    tags_json = ?2,
    notes     = ?3
WHERE id = ?4
`

type UpdateFindingStatusParams struct {
	Status   string
	TagsJson string
	Notes    string
	ID       int64
}

func (q *Queries) UpdateFindingStatus(ctx context.Context, arg UpdateFindingStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateFindingStatus,
		arg.Status,
		arg.TagsJson,
		arg.Notes,
		arg.ID,
	)
	return err
}

const upsertFinding = `-- name: UpsertFinding :one

INSERT INTO findings (
    template_signature, tool, host_id, port_id, url_id, path,
    severity, status, title, description, evidence, matched_at,
    cvss_score, tags_json, notes, raw_json,
    first_seen_at, last_seen_at, target_id
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6,
    ?7, 'open', ?8, ?9, ?10, ?11,
    ?12, '[]', '', ?13,
    ?14, ?14, ?15
)
ON CONFLICT(target_id, template_signature, tool, COALESCE(host_id, 0), COALESCE(port_id, 0), path)
DO UPDATE SET
    last_seen_at = excluded.last_seen_at,
    description  = excluded.description,
    evidence     = excluded.evidence,
    matched_at   = excluded.matched_at,
    raw_json     = COALESCE(excluded.raw_json, findings.raw_json),
    -- Worst-severity-wins on re-observation; ordering is critical>high>medium>low>info>unknown.
    severity = CASE
        WHEN findings.severity = 'critical' THEN findings.severity
        WHEN excluded.severity = 'critical' THEN excluded.severity
        WHEN findings.severity = 'high'     THEN findings.severity
        WHEN excluded.severity = 'high'     THEN excluded.severity
        WHEN findings.severity = 'medium'   THEN findings.severity
        WHEN excluded.severity = 'medium'   THEN excluded.severity
        WHEN findings.severity = 'low'      THEN findings.severity
        WHEN excluded.severity = 'low'      THEN excluded.severity
        WHEN findings.severity = 'info'     THEN findings.severity
        ELSE excluded.severity
    END,
    cvss_score = CASE
        WHEN excluded.cvss_score IS NULL THEN findings.cvss_score
        WHEN findings.cvss_score IS NULL THEN excluded.cvss_score
        WHEN excluded.cvss_score > findings.cvss_score THEN excluded.cvss_score
        ELSE findings.cvss_score
    END
RETURNING id, template_signature, tool, host_id, port_id, url_id, path, severity, status, title, description, evidence, matched_at, cvss_score, tags_json, notes, raw_json, first_seen_at, last_seen_at, target_id
`

type UpsertFindingParams struct {
	TemplateSignature string
	Tool              string
	HostID            *int64
	PortID            *int64
	URLID             *int64
	Path              string
	Severity          string
	Title             string
	Description       string
	Evidence          string
	MatchedAt         string
	CVSSScore         *float64
	RawJson           *string
	Now               int64
	// TargetID is ?15 -- appended rather than placed first so the existing
	// placeholder numbering (and every other caller argument) is untouched.
	// It is part of the ux_findings_dedup key: an empty value would put every
	// engagement's findings back in one shared row.
	TargetID string
}

// Phase 1, Plan 05 -- findings query file.
//
// Natural key uses COALESCE(host_id,0)/COALESCE(port_id,0) to keep
// NULL-bearing rows comparable; matches idx_findings_dedup.
//
// Triage state (status, tags_json, notes) survives re-scan UPSERTs
// (DAT-03). Severity may be elevated on re-observation (worst-wins),
// but never demoted.
//
// ListFindingsBySeverityForTarget is Q2 of the EXPLAIN gate.
func (q *Queries) UpsertFinding(ctx context.Context, arg UpsertFindingParams) (Finding, error) {
	row := q.db.QueryRowContext(ctx, upsertFinding,
		arg.TemplateSignature,
		arg.Tool,
		arg.HostID,
		arg.PortID,
		arg.URLID,
		arg.Path,
		arg.Severity,
		arg.Title,
		arg.Description,
		arg.Evidence,
		arg.MatchedAt,
		arg.CVSSScore,
		arg.RawJson,
		arg.Now,
		arg.TargetID,
	)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.TemplateSignature,
		&i.Tool,
		&i.HostID,
		&i.PortID,
		&i.URLID,
		&i.Path,
		&i.Severity,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.Evidence,
		&i.MatchedAt,
		&i.CVSSScore,
		&i.TagsJson,
		&i.Notes,
		&i.RawJson,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.TargetID,
	)
	return i, err
}
