// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hosts.sql

package sqlcgen

import (
	"context"
)

const attachHostToTarget = `-- name: AttachHostToTarget :exec
INSERT INTO target_host(target_id, host_id) VALUES (?, ?)
ON CONFLICT(target_id, host_id) DO NOTHING
`

type AttachHostToTargetParams struct {
	TargetID string
	HostID   int64
}

func (q *Queries) AttachHostToTarget(ctx context.Context, arg AttachHostToTargetParams) error {
	_, err := q.db.ExecContext(ctx, attachHostToTarget, arg.TargetID, arg.HostID)
	return err
}

const countHostsForTarget = `-- name: CountHostsForTarget :one
SELECT COUNT(*) FROM target_host WHERE target_id = ?
`

func (q *Queries) CountHostsForTarget(ctx context.Context, targetID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countHostsForTarget, targetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getHost = `-- name: GetHost :one
SELECT id, fqdn, ip_current, asn, asn_org, cdn, first_seen_at, last_seen_at, status, tags_json, notes, raw_json FROM hosts WHERE id = ? LIMIT 1
`

func (q *Queries) GetHost(ctx context.Context, id int64) (Host, error) {
	row := q.db.QueryRowContext(ctx, getHost, id)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.FQDN,
		&i.IpCurrent,
		&i.ASN,
		&i.ASNOrg,
		&i.CDN,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Status,
		&i.TagsJson,
		&i.Notes,
		&i.RawJson,
	)
	return i, err
}

const getHostByFQDN = `-- name: GetHostByFQDN :one
SELECT id, fqdn, ip_current, asn, asn_org, cdn, first_seen_at, last_seen_at, status, tags_json, notes, raw_json FROM hosts WHERE fqdn = ? LIMIT 1
`

func (q *Queries) GetHostByFQDN(ctx context.Context, fqdn string) (Host, error) {
	row := q.db.QueryRowContext(ctx, getHostByFQDN, fqdn)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.FQDN,
		&i.IpCurrent,
		&i.ASN,
		&i.ASNOrg,
		&i.CDN,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Status,
		&i.TagsJson,
		&i.Notes,
		&i.RawJson,
	)
	return i, err
}

const listHostsCursor = `-- name: ListHostsCursor :many
SELECT h.id, h.fqdn, h.ip_current, h.asn, h.asn_org, h.cdn,
       h.first_seen_at, h.last_seen_at, h.status, h.tags_json,
       h.notes, h.raw_json
FROM hosts h
LEFT JOIN target_host th ON th.host_id = h.id
WHERE (?1 = '' OR th.target_id = ?1)
  AND (?2 = '' OR
       (?2 = 'true'  AND h.cdn IS NOT NULL AND h.cdn <> '') OR
       (?2 = 'false' AND (h.cdn IS NULL OR h.cdn = '')))
  AND (?3 = 0 OR
       h.last_seen_at < ?3 OR
       (h.last_seen_at = ?3 AND h.id < ?4))
ORDER BY h.last_seen_at DESC, h.id DESC
LIMIT ?5
`

type ListHostsCursorParams struct {
	TargetID     interface{}
	CdnFilter    interface{}
	CursorSeenAt interface{}
	CursorLastID int64
	RowLimit     int64
}

// Plan 04-04 - cursor-paginated hosts list for GET /api/v1/hosts.
//
// Filter columns: target_id (via target_host join), cdn ("true"/"false"/"" - empty disables filter).
// Cursor: composite (last_seen_at, id) - Disc-02 for non-ULID canonical
// assets. Tuple comparison (last_seen_at < cursor_seen_at OR
// (last_seen_at = cursor_seen_at AND id < cursor_last_id)) keeps
// ordering monotonic when two hosts share a last_seen_at.
//
// cursor_seen_at = 0 -> first page (no cursor lower bound).
func (q *Queries) ListHostsCursor(ctx context.Context, arg ListHostsCursorParams) ([]Host, error) {
	rows, err := q.db.QueryContext(ctx, listHostsCursor,
		arg.TargetID,
		arg.CdnFilter,
		arg.CursorSeenAt,
		arg.CursorLastID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Host
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.FQDN,
			&i.IpCurrent,
			&i.ASN,
			&i.ASNOrg,
			&i.CDN,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.Status,
			&i.TagsJson,
			&i.Notes,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostsForTarget = `-- name: ListHostsForTarget :many
SELECT h.id, h.fqdn, h.ip_current, h.status, h.tags_json
FROM target_host th
JOIN hosts h ON h.id = th.host_id
WHERE th.target_id = ?
ORDER BY h.fqdn
LIMIT ? OFFSET ?
`

type ListHostsForTargetParams struct {
	TargetID string
	Limit    int64
	Offset   int64
}

type ListHostsForTargetRow struct {
	ID        int64
	FQDN      string
	IpCurrent *string
	Status    string
	TagsJson  string
}

func (q *Queries) ListHostsForTarget(ctx context.Context, arg ListHostsForTargetParams) ([]ListHostsForTargetRow, error) {
	rows, err := q.db.QueryContext(ctx, listHostsForTarget, arg.TargetID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHostsForTargetRow
	for rows.Next() {
		var i ListHostsForTargetRow
		if err := rows.Scan(
			&i.ID,
			&i.FQDN,
			&i.IpCurrent,
			&i.Status,
			&i.TagsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHostTriage = `-- name: UpdateHostTriage :exec
UPDATE hosts SET
    status    = ?1,
    tags_json = ?2,
    notes     = ?3
WHERE id = ?4
`

type UpdateHostTriageParams struct {
	Status   string
	TagsJson string
	Notes    string
	ID       int64
}

func (q *Queries) UpdateHostTriage(ctx context.Context, arg UpdateHostTriageParams) error {
	_, err := q.db.ExecContext(ctx, updateHostTriage,
		arg.Status,
		arg.TagsJson,
		arg.Notes,
		arg.ID,
	)
	return err
}

const upsertHost = `-- name: UpsertHost :one

INSERT INTO hosts (
    fqdn, ip_current, asn, asn_org, cdn,
    first_seen_at, last_seen_at, status, tags_json, notes, raw_json
) VALUES (
    ?1, ?2, ?3, ?4, ?5,
    ?6, ?6, 'new', '[]', '', ?7
)
ON CONFLICT(fqdn) DO UPDATE SET
    last_seen_at = excluded.last_seen_at,
    ip_current   = COALESCE(excluded.ip_current, hosts.ip_current),
    asn          = COALESCE(excluded.asn, hosts.asn),
    asn_org      = COALESCE(excluded.asn_org, hosts.asn_org),
    cdn          = COALESCE(excluded.cdn, hosts.cdn),
    raw_json     = COALESCE(excluded.raw_json, hosts.raw_json)
RETURNING id, fqdn, ip_current, asn, asn_org, cdn, first_seen_at, last_seen_at, status, tags_json, notes, raw_json
`

type UpsertHostParams struct {
	FQDN      string
	IpCurrent *string
	ASN       *int64
	ASNOrg    *string
	CDN       *string
	Now       int64
	RawJson   *string
}

// Phase 1, Plan 05 -- hosts query file (canonical asset table).
//
// Mirrors RESEARCH Sec5.3 verbatim. UPSERT preserves the canonical-row
// triage state (status, tags_json, notes) -- the DAT-03 contract. The
// ON CONFLICT branch only refreshes observation fields and last_seen_at.
//
// ListHostsForTarget is Q1 of the EXPLAIN gate; CountHostsForTarget
// powers paginator UI; UpdateHostTriage is the triage write path.
func (q *Queries) UpsertHost(ctx context.Context, arg UpsertHostParams) (Host, error) {
	row := q.db.QueryRowContext(ctx, upsertHost,
		arg.FQDN,
		arg.IpCurrent,
		arg.ASN,
		arg.ASNOrg,
		arg.CDN,
		arg.Now,
		arg.RawJson,
	)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.FQDN,
		&i.IpCurrent,
		&i.ASN,
		&i.ASNOrg,
		&i.CDN,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Status,
		&i.TagsJson,
		&i.Notes,
		&i.RawJson,
	)
	return i, err
}
