// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: js.sql

package sqlcgen

import (
	"context"
)

const attachJSToTarget = `-- name: AttachJSToTarget :exec
INSERT INTO target_js(target_id, js_id) VALUES (?, ?)
ON CONFLICT(target_id, js_id) DO NOTHING
`

type AttachJSToTargetParams struct {
	TargetID string
	JSID     int64
}

func (q *Queries) AttachJSToTarget(ctx context.Context, arg AttachJSToTargetParams) error {
	_, err := q.db.ExecContext(ctx, attachJSToTarget, arg.TargetID, arg.JSID)
	return err
}

const getJSFile = `-- name: GetJSFile :one
SELECT id, sha256, size_bytes, host_id, source_url_id, storage_path, secrets_count, first_seen_at, last_seen_at, tags_json, notes, raw_json FROM js_files WHERE id = ? LIMIT 1
`

func (q *Queries) GetJSFile(ctx context.Context, id int64) (JsFile, error) {
	row := q.db.QueryRowContext(ctx, getJSFile, id)
	var i JsFile
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.SizeBytes,
		&i.HostID,
		&i.SourceUrlID,
		&i.StoragePath,
		&i.SecretsCount,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.TagsJson,
		&i.Notes,
		&i.RawJson,
	)
	return i, err
}

const getJSFileBySHA256 = `-- name: GetJSFileBySHA256 :one
SELECT id, sha256, size_bytes, host_id, source_url_id, storage_path, secrets_count, first_seen_at, last_seen_at, tags_json, notes, raw_json FROM js_files WHERE sha256 = ? LIMIT 1
`

func (q *Queries) GetJSFileBySHA256(ctx context.Context, sha256 []byte) (JsFile, error) {
	row := q.db.QueryRowContext(ctx, getJSFileBySHA256, sha256)
	var i JsFile
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.SizeBytes,
		&i.HostID,
		&i.SourceUrlID,
		&i.StoragePath,
		&i.SecretsCount,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.TagsJson,
		&i.Notes,
		&i.RawJson,
	)
	return i, err
}

const listJSCursor = `-- name: ListJSCursor :many
SELECT j.id, j.sha256, j.size_bytes, j.host_id, j.source_url_id,
       j.storage_path, j.secrets_count, j.first_seen_at, j.last_seen_at,
       j.tags_json, j.notes, j.raw_json
FROM js_files j
WHERE (?1 = 0 OR j.host_id = ?1)
  AND (?2 = 0 OR
       j.last_seen_at < ?2 OR
       (j.last_seen_at = ?2 AND j.id < ?3))
ORDER BY j.last_seen_at DESC, j.id DESC
LIMIT ?4
`

type ListJSCursorParams struct {
	HostIDFilter interface{}
	CursorSeenAt interface{}
	CursorLastID int64
	RowLimit     int64
}

// Plan 04-04 - cursor-paginated JS list for GET /api/v1/js.
//
// Filter: host_id (0 disables).
// Cursor: composite (last_seen_at, id) per Disc-02.
func (q *Queries) ListJSCursor(ctx context.Context, arg ListJSCursorParams) ([]JsFile, error) {
	rows, err := q.db.QueryContext(ctx, listJSCursor,
		arg.HostIDFilter,
		arg.CursorSeenAt,
		arg.CursorLastID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JsFile
	for rows.Next() {
		var i JsFile
		if err := rows.Scan(
			&i.ID,
			&i.Sha256,
			&i.SizeBytes,
			&i.HostID,
			&i.SourceUrlID,
			&i.StoragePath,
			&i.SecretsCount,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.TagsJson,
			&i.Notes,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJSFilesForTarget = `-- name: ListJSFilesForTarget :many
SELECT j.id, j.sha256, j.size_bytes, j.host_id, j.source_url_id, j.storage_path, j.secrets_count, j.first_seen_at, j.last_seen_at, j.tags_json, j.notes, j.raw_json
FROM target_js tj
JOIN js_files j ON j.id = tj.js_id
WHERE tj.target_id = ?
ORDER BY j.last_seen_at DESC
LIMIT ? OFFSET ?
`

type ListJSFilesForTargetParams struct {
	TargetID string
	Limit    int64
	Offset   int64
}

func (q *Queries) ListJSFilesForTarget(ctx context.Context, arg ListJSFilesForTargetParams) ([]JsFile, error) {
	rows, err := q.db.QueryContext(ctx, listJSFilesForTarget, arg.TargetID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JsFile
	for rows.Next() {
		var i JsFile
		if err := rows.Scan(
			&i.ID,
			&i.Sha256,
			&i.SizeBytes,
			&i.HostID,
			&i.SourceUrlID,
			&i.StoragePath,
			&i.SecretsCount,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.TagsJson,
			&i.Notes,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertJSFile = `-- name: UpsertJSFile :one

INSERT INTO js_files (
    sha256, size_bytes, host_id, source_url_id,
    storage_path, secrets_count,
    first_seen_at, last_seen_at, tags_json, notes, raw_json
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6,
    ?7, ?7, '[]', '', ?8
)
ON CONFLICT(sha256) DO UPDATE SET
    last_seen_at  = excluded.last_seen_at,
    secrets_count = excluded.secrets_count,
    storage_path  = COALESCE(excluded.storage_path, js_files.storage_path),
    raw_json      = COALESCE(excluded.raw_json, js_files.raw_json)
RETURNING id, sha256, size_bytes, host_id, source_url_id, storage_path, secrets_count, first_seen_at, last_seen_at, tags_json, notes, raw_json
`

type UpsertJSFileParams struct {
	Sha256       []byte
	SizeBytes    int64
	HostID       *int64
	SourceUrlID  *int64
	StoragePath  *string
	SecretsCount int64
	Now          int64
	RawJson      *string
}

// Phase 1, Plan 05 -- js_files query file.
//
// JavaScript artifacts are content-addressed by SHA-256. The UPSERT
// refreshes last_seen_at and secrets_count when the same JS file is
// re-observed; tags_json/notes are preserved.
func (q *Queries) UpsertJSFile(ctx context.Context, arg UpsertJSFileParams) (JsFile, error) {
	row := q.db.QueryRowContext(ctx, upsertJSFile,
		arg.Sha256,
		arg.SizeBytes,
		arg.HostID,
		arg.SourceUrlID,
		arg.StoragePath,
		arg.SecretsCount,
		arg.Now,
		arg.RawJson,
	)
	var i JsFile
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.SizeBytes,
		&i.HostID,
		&i.SourceUrlID,
		&i.StoragePath,
		&i.SecretsCount,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.TagsJson,
		&i.Notes,
		&i.RawJson,
	)
	return i, err
}
