// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

type Company struct {
	ID          string
	Name        string
	Description string
	CreatedAt   int64
	UpdatedAt   int64
}

type Finding struct {
	ID                int64
	TemplateSignature string
	Tool              string
	HostID            *int64
	PortID            *int64
	URLID             *int64
	Path              string
	Severity          string
	Status            string
	Title             string
	Description       string
	Evidence          string
	MatchedAt         string
	CVSSScore         *float64
	TagsJson          string
	Notes             string
	RawJson           *string
	FirstSeenAt       int64
	LastSeenAt        int64
	// TargetID scopes the finding to one engagement. It is LAST because the
	// column is last in the table (see schema.sql), which in turn is what makes
	// a migrated database textually identical to a fresh one.
	TargetID string
}

type FindingsFt struct {
	TemplateSignature string
	Title             string
	Description       string
	MatchedAt         string
}

type Host struct {
	ID          int64
	FQDN        string
	IpCurrent   *string
	ASN         *int64
	ASNOrg      *string
	CDN         *string
	FirstSeenAt int64
	LastSeenAt  int64
	Status      string
	TagsJson    string
	Notes       string
	RawJson     *string
}

type JsFile struct {
	ID           int64
	Sha256       []byte
	SizeBytes    int64
	HostID       *int64
	SourceUrlID  *int64
	StoragePath  *string
	SecretsCount int64
	FirstSeenAt  int64
	LastSeenAt   int64
	TagsJson     string
	Notes        string
	RawJson      *string
}

type Port struct {
	ID             int64
	HostID         int64
	PortNumber     int64
	Protocol       string
	State          string
	ServiceName    *string
	ServiceVersion *string
	Banner         *string
	FirstSeenAt    int64
	LastSeenAt     int64
	TagsJson       string
	RawJson        *string
}

type Scan struct {
	ID                  string
	TargetID            string
	Mode                string
	Status              string
	StartedAt           int64
	FinishedAt          *int64
	ExitCode            *int64
	ReconftwVersion     *string
	ToolVersionsJson    *string
	RawArgsJson         string
	ConfigOverridesJson string
	OutputDir           string
	CancelledBy         *string
	FindingsCount       int64
	SubdomainCount      int64
	UrlCount            int64
}

type ScanObservation struct {
	ID         int64
	ScanID     string
	TargetID   string
	AssetKind  string
	AssetID    int64
	ObservedAt int64
	RawJson    *string
}

type Setting struct {
	ID             int64
	Scope          string
	TargetID       *string
	Key            string
	ValuePlain     *string
	ValueEncrypted []byte
	IsSecret       int64
	LastTestAt     *int64
	LastTestOk     *int64
	CreatedAt      int64
	UpdatedAt      int64
}

type Target struct {
	ID          string
	Name        string
	Description string
	CompanyID   *string
	ReconDir    string
	TagsJson    string
	Notes       string
	CreatedAt   int64
	UpdatedAt   int64
}

type TargetFinding struct {
	TargetID  string
	FindingID int64
}

type TargetHost struct {
	TargetID string
	HostID   int64
}

type TargetJ struct {
	TargetID string
	JSID     int64
}

type TargetPort struct {
	TargetID string
	PortID   int64
}

type TargetRoot struct {
	ID        int64
	TargetID  string
	RootValue string
	RootType  string
	ScopeKind string
	CreatedAt int64
}

type TargetUrl struct {
	TargetID string
	URLID    int64
}

type URL struct {
	ID             int64
	URL            string
	UrlHash        []byte
	Scheme         string
	HostID         *int64
	Port           *int64
	Path           string
	QueryCanonical string
	StatusCode     *int64
	ContentType    *string
	ContentLength  *int64
	Title          *string
	TechJson       *string
	ScreenshotPath *string
	FirstSeenAt    int64
	LastSeenAt     int64
	Status         string
	TagsJson       string
	Notes          string
	RawJson        *string
}

type UrlsFt struct {
	Path           string
	QueryCanonical string
	Title          string
	ContentType    string
}
