// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ports.sql

package sqlcgen

import (
	"context"
)

const attachPortToTarget = `-- name: AttachPortToTarget :exec
INSERT INTO target_port(target_id, port_id) VALUES (?, ?)
ON CONFLICT(target_id, port_id) DO NOTHING
`

type AttachPortToTargetParams struct {
	TargetID string
	PortID   int64
}

func (q *Queries) AttachPortToTarget(ctx context.Context, arg AttachPortToTargetParams) error {
	_, err := q.db.ExecContext(ctx, attachPortToTarget, arg.TargetID, arg.PortID)
	return err
}

const getPort = `-- name: GetPort :one
SELECT id, host_id, port_number, protocol, state, service_name, service_version, banner, first_seen_at, last_seen_at, tags_json, raw_json FROM ports WHERE id = ? LIMIT 1
`

func (q *Queries) GetPort(ctx context.Context, id int64) (Port, error) {
	row := q.db.QueryRowContext(ctx, getPort, id)
	var i Port
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.PortNumber,
		&i.Protocol,
		&i.State,
		&i.ServiceName,
		&i.ServiceVersion,
		&i.Banner,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.TagsJson,
		&i.RawJson,
	)
	return i, err
}

const listPortsForHost = `-- name: ListPortsForHost :many
SELECT id, host_id, port_number, protocol, state, service_name, service_version, banner, first_seen_at, last_seen_at, tags_json, raw_json FROM ports
WHERE host_id = ?
ORDER BY port_number
`

func (q *Queries) ListPortsForHost(ctx context.Context, hostID int64) ([]Port, error) {
	rows, err := q.db.QueryContext(ctx, listPortsForHost, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Port
	for rows.Next() {
		var i Port
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.PortNumber,
			&i.Protocol,
			&i.State,
			&i.ServiceName,
			&i.ServiceVersion,
			&i.Banner,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.TagsJson,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPortsForTarget = `-- name: ListPortsForTarget :many
SELECT p.id, p.host_id, p.port_number, p.protocol, p.state, p.service_name, p.service_version, p.banner, p.first_seen_at, p.last_seen_at, p.tags_json, p.raw_json
FROM target_port tp
JOIN ports p ON p.id = tp.port_id
WHERE tp.target_id = ?
ORDER BY p.host_id, p.port_number
LIMIT ? OFFSET ?
`

type ListPortsForTargetParams struct {
	TargetID string
	Limit    int64
	Offset   int64
}

func (q *Queries) ListPortsForTarget(ctx context.Context, arg ListPortsForTargetParams) ([]Port, error) {
	rows, err := q.db.QueryContext(ctx, listPortsForTarget, arg.TargetID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Port
	for rows.Next() {
		var i Port
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.PortNumber,
			&i.Protocol,
			&i.State,
			&i.ServiceName,
			&i.ServiceVersion,
			&i.Banner,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.TagsJson,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePortBanner = `-- name: UpdatePortBanner :exec
UPDATE ports SET
    banner       = ?1,
    last_seen_at = ?2
WHERE id = ?3
`

type UpdatePortBannerParams struct {
	Banner     *string
	LastSeenAt int64
	ID         int64
}

func (q *Queries) UpdatePortBanner(ctx context.Context, arg UpdatePortBannerParams) error {
	_, err := q.db.ExecContext(ctx, updatePortBanner, arg.Banner, arg.LastSeenAt, arg.ID)
	return err
}

const upsertPort = `-- name: UpsertPort :one

INSERT INTO ports (
    host_id, port_number, protocol, state,
    service_name, service_version, banner,
    first_seen_at, last_seen_at, tags_json, raw_json
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7,
    ?8, ?8, '[]', ?9
)
ON CONFLICT(host_id, port_number, protocol) DO UPDATE SET
    last_seen_at    = excluded.last_seen_at,
    state           = excluded.state,
    service_name    = COALESCE(excluded.service_name, ports.service_name),
    service_version = COALESCE(excluded.service_version, ports.service_version),
    banner          = COALESCE(excluded.banner, ports.banner),
    raw_json        = COALESCE(excluded.raw_json, ports.raw_json)
RETURNING id, host_id, port_number, protocol, state, service_name, service_version, banner, first_seen_at, last_seen_at, tags_json, raw_json
`

type UpsertPortParams struct {
	HostID         int64
	PortNumber     int64
	Protocol       string
	State          string
	ServiceName    *string
	ServiceVersion *string
	Banner         *string
	Now            int64
	RawJson        *string
}

// Phase 1, Plan 05 -- ports query file.
//
// Natural key is (host_id, port_number, protocol). UPSERT refreshes
// observation fields (state, service_name, service_version, banner)
// and last_seen_at; tags_json is preserved across re-scans.
func (q *Queries) UpsertPort(ctx context.Context, arg UpsertPortParams) (Port, error) {
	row := q.db.QueryRowContext(ctx, upsertPort,
		arg.HostID,
		arg.PortNumber,
		arg.Protocol,
		arg.State,
		arg.ServiceName,
		arg.ServiceVersion,
		arg.Banner,
		arg.Now,
		arg.RawJson,
	)
	var i Port
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.PortNumber,
		&i.Protocol,
		&i.State,
		&i.ServiceName,
		&i.ServiceVersion,
		&i.Banner,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.TagsJson,
		&i.RawJson,
	)
	return i, err
}
