// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	AttachFindingToTarget(ctx context.Context, arg AttachFindingToTargetParams) error
	AttachHostToTarget(ctx context.Context, arg AttachHostToTargetParams) error
	AttachJSToTarget(ctx context.Context, arg AttachJSToTargetParams) error
	AttachPortToTarget(ctx context.Context, arg AttachPortToTargetParams) error
	AttachURLToTarget(ctx context.Context, arg AttachURLToTargetParams) error
	CountCompanies(ctx context.Context) (int64, error)
	CountHostsForTarget(ctx context.Context, targetID string) (int64, error)
	CountScansForTarget(ctx context.Context, targetID string) (int64, error)
	CountTargets(ctx context.Context) (int64, error)
	// Plain INSERT (not UPSERT). ScansCreate-style handlers want a hard
	// error on duplicate id; the UpsertCompany helper from Phase 1 stays
	// available for ingestion paths.
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error)
	// Phase 1, Plan 05 -- scans query file.
	//
	// Scans are immutable run records. Status transitions go queued ->
	// running -> {completed,failed,cancelled,incomplete}. UpdateScanCounts
	// is called by Phase 3's OnPhaseEnd at each module boundary.
	CreateScan(ctx context.Context, arg CreateScanParams) (Scan, error)
	// Phase 1, Plan 05 -- targets query file.
	//
	// The id ULID is supplied by the caller (NewTargetID).
	// Engagement-level entity; multiple roots live in `target_roots`.
	CreateTarget(ctx context.Context, arg CreateTargetParams) (Target, error)
	DeleteCompany(ctx context.Context, id string) error
	DeleteGlobalSetting(ctx context.Context, key string) error
	DeleteTarget(ctx context.Context, id string) error
	DeleteTargetRoot(ctx context.Context, id int64) error
	DeleteTargetSetting(ctx context.Context, arg DeleteTargetSettingParams) error
	// Returns rows in scan B that are NOT in scan A, scoped to target T.
	// Args (positional): targetIDB, scanB, targetIDA, scanA.
	// Both halves use idx_scan_obs_unique (RESEARCH Sec4.2 Q3 expected plan).
	// Columns are fully table-qualified to disambiguate the EXCEPT compound
	// (sqlc rejects `WHERE target_id = ?` in both halves as "ambiguous").
	DiffBetweenScans(ctx context.Context, arg DiffBetweenScansParams) ([]DiffBetweenScansRow, error)
	// Findings diff for ScansDiff handler. asset_kind = 'finding' restricts.
	// Returns finding_id + template_signature + severity + title for the
	// API DTO.
	DiffScansFindings(ctx context.Context, arg DiffScansFindingsParams) ([]DiffScansFindingsRow, error)
	// Returns host asset_ids that appear in scan_a but not scan_b (or vice
	// versa via swap of args). Used by ScansDiff handler -- called twice
	// (added: scan_a=to, scan_b=from; removed: scan_a=from, scan_b=to).
	// asset_kind = 'host' restricts the polymorphic scan_observation column.
	// Returns host_id + fqdn for the API DTO.
	DiffScansHosts(ctx context.Context, arg DiffScansHostsParams) ([]DiffScansHostsRow, error)
	// URLs diff for ScansDiff handler. asset_kind = 'url' restricts the
	// polymorphic column. Returns url_id + url for the API DTO.
	DiffScansURLs(ctx context.Context, arg DiffScansURLsParams) ([]DiffScansURLsRow, error)
	GetCompany(ctx context.Context, id string) (Company, error)
	GetFinding(ctx context.Context, id int64) (Finding, error)
	// Phase 1, Plan 05 -- settings query file.
	//
	// Two scopes: 'global' and 'target'. Both use partial UNIQUE indexes
	// (idx_settings_global, idx_settings_target). Phase 6 will encrypt
	// secrets at rest; the T-V6-1 CHECK constraint already prevents
	// accidental plaintext when is_secret=1.
	GetGlobalSetting(ctx context.Context, key string) (Setting, error)
	GetHost(ctx context.Context, id int64) (Host, error)
	GetHostByFQDN(ctx context.Context, fqdn string) (Host, error)
	GetJSFile(ctx context.Context, id int64) (JsFile, error)
	GetJSFileBySHA256(ctx context.Context, sha256 []byte) (JsFile, error)
	// GetLatestCompletedScanForTarget returns the most recent completed scan
	// for the given target_id. Returns sql.ErrNoRows when none exists.
	// Phase 10, Plan 01.
	GetLatestCompletedScanForTarget(ctx context.Context, targetID string) (Scan, error)
	GetPort(ctx context.Context, id int64) (Port, error)
	GetScan(ctx context.Context, id string) (Scan, error)
	GetTarget(ctx context.Context, id string) (Target, error)
	GetTargetByName(ctx context.Context, name string) (Target, error)
	GetTargetSetting(ctx context.Context, arg GetTargetSettingParams) (Setting, error)
	GetURL(ctx context.Context, id int64) (URL, error)
	GetURLByHash(ctx context.Context, urlHash []byte) (URL, error)
	// Phase 1, Plan 05 -- scan_observation query file.
	//
	// Polymorphic per-scan observation triplet (scan_id, asset_kind, asset_id).
	// Unique on (scan_id, asset_kind, asset_id) -- the same scan cannot observe
	// the same asset twice. DiffBetweenScans is Q3 of the EXPLAIN gate.
	InsertObservation(ctx context.Context, arg InsertObservationParams) error
	// Phase 1, Plan 05 -- target_roots query file.
	//
	// Each target has 1..N roots; scope_kind=include defines the in-scope
	// root set; scope_kind=exclude carves holes (Phase 3 ingest gates each
	// row through scope.ApplyExclusions which consults these queries).
	//
	// Phase 3 will call ListIncludeRoots+ListExcludeRoots once per scan
	// on the writer pool to seed its in-memory scope cache.
	InsertTargetRoot(ctx context.Context, arg InsertTargetRootParams) (TargetRoot, error)
	ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]Company, error)
	// Cursor-based pagination by id DESC. Caller passes the last_id from the
	// previous page; for the first page, caller passes the ULID-max sentinel
	// (26 'Z' chars, larger than any real Crockford-base32 ULID). D-16.
	ListCompaniesCursor(ctx context.Context, arg ListCompaniesCursorParams) ([]Company, error)
	ListExcludeRoots(ctx context.Context, targetID string) ([]TargetRoot, error)
	ListFindingsBySeverityForTarget(ctx context.Context, arg ListFindingsBySeverityForTargetParams) ([]ListFindingsBySeverityForTargetRow, error)
	// Plan 04-04 - cursor-paginated findings list for GET /api/v1/findings.
	//
	// Filter columns: target_id (via target_finding join), host_id, severity, status.
	// Cursor: id < cursor_last_id (0 -> first page); findings.id is INTEGER
	// auto-increment, so a single-column cursor on id DESC is sufficient and
	// monotonic across concurrent UPSERTs (new rows always get a higher id).
	// Tag filter deferred to Phase 6 (tags live in JSON column; no normalized
	// finding_tag table in the v1 schema).
	ListFindingsCursor(ctx context.Context, arg ListFindingsCursorParams) ([]Finding, error)
	ListFindingsForTarget(ctx context.Context, arg ListFindingsForTargetParams) ([]Finding, error)
	// Plan 04-04 - cursor-paginated hosts list for GET /api/v1/hosts.
	//
	// Filter columns: target_id (via target_host join), cdn ("true"/"false"/"" - empty disables filter).
	// Cursor: composite (last_seen_at, id) - Disc-02 for non-ULID canonical
	// assets. Tuple comparison (last_seen_at < cursor_seen_at OR
	// (last_seen_at = cursor_seen_at AND id < cursor_last_id)) keeps
	// ordering monotonic when two hosts share a last_seen_at.
	//
	// cursor_seen_at = 0 -> first page (no cursor lower bound).
	ListHostsCursor(ctx context.Context, arg ListHostsCursorParams) ([]Host, error)
	ListHostsForTarget(ctx context.Context, arg ListHostsForTargetParams) ([]ListHostsForTargetRow, error)
	ListIncludeRoots(ctx context.Context, targetID string) ([]TargetRoot, error)
	// Plan 04-04 - cursor-paginated JS list for GET /api/v1/js.
	//
	// Filter: host_id (0 disables).
	// Cursor: composite (last_seen_at, id) per Disc-02.
	ListJSCursor(ctx context.Context, arg ListJSCursorParams) ([]JsFile, error)
	ListJSFilesForTarget(ctx context.Context, arg ListJSFilesForTargetParams) ([]JsFile, error)
	ListObservationsForAsset(ctx context.Context, arg ListObservationsForAssetParams) ([]ScanObservation, error)
	ListObservationsForScan(ctx context.Context, scanID string) ([]ScanObservation, error)
	ListPortsForHost(ctx context.Context, hostID int64) ([]Port, error)
	ListPortsForTarget(ctx context.Context, arg ListPortsForTargetParams) ([]Port, error)
	// Cursor-based pagination by id DESC, with optional target_id and status
	// filters. Caller passes empty string for filters that should match all.
	// For the first page, caller passes the ULID-max sentinel (26 'Z' chars)
	// as cursor. ULIDs lex-sort. D-16.
	ListScansCursor(ctx context.Context, arg ListScansCursorParams) ([]Scan, error)
	ListScansForTarget(ctx context.Context, arg ListScansForTargetParams) ([]Scan, error)
	ListSettingsForTarget(ctx context.Context, targetID *string) ([]Setting, error)
	ListTargetRoots(ctx context.Context, targetID string) ([]TargetRoot, error)
	ListTargets(ctx context.Context, arg ListTargetsParams) ([]Target, error)
	ListTargetsByCompany(ctx context.Context, arg ListTargetsByCompanyParams) ([]Target, error)
	// Cursor-based pagination by id DESC. Caller passes the last_id from the
	// previous page; for the first page, caller passes a ULID-max-sentinel
	// ('ZZZZZZZZZZZZZZZZZZZZZZZZZZ' -- 26 'Z's, greater than every real ULID
	// in Crockford base32). ULIDs are lexicographically sortable so the
	// PRIMARY KEY index on targets.id satisfies ORDER BY id DESC. D-16.
	ListTargetsCursor(ctx context.Context, arg ListTargetsCursorParams) ([]Target, error)
	// Plan 04-04 - cursor-paginated URL list for GET /api/v1/urls.
	//
	// Filter columns: host_id (0 disables), status_code (0 disables), content_type ("" disables).
	// Cursor: composite (last_seen_at, id) - Disc-02 for non-ULID canonical
	// assets. SQLite >= 3.15 supports tuple comparison but sqlc parses the
	// explicit form more reliably.
	ListURLsCursor(ctx context.Context, arg ListURLsCursorParams) ([]URL, error)
	// Variant used by the screenshots handler - lists URLs that have a
	// non-empty screenshot_path, filtered by host_id. Reuses the urls table
	// because the v1 schema does not split screenshots into a dedicated
	// table (screenshot_path is a URL column).
	ListURLsCursorByHost(ctx context.Context, arg ListURLsCursorByHostParams) ([]URL, error)
	ListURLsForHost(ctx context.Context, arg ListURLsForHostParams) ([]URL, error)
	ListURLsForTarget(ctx context.Context, arg ListURLsForTargetParams) ([]URL, error)
	// Plan 04-04 - single-finding triage patch (status + tags_json + notes).
	// COALESCE(sqlc.narg, col) keeps the column unchanged when the named
	// nullable parameter is NULL. State-machine transition rules deferred
	// to Phase 6 UX-02; this query accepts any value within the schema
	// CHECK constraint on findings.status.
	PatchFinding(ctx context.Context, arg PatchFindingParams) (Finding, error)
	// Plan 04-04 - single-URL tag patch (POST /api/v1/urls/bulk loop body).
	// Atomic per-row update inside WithWriteTx; soft-atomicity surfaced via
	// per-id errors[] in handler response.
	PatchURLTags(ctx context.Context, arg PatchURLTagsParams) (URL, error)
	SearchFindings(ctx context.Context, arg SearchFindingsParams) ([]SearchFindingsRow, error)
	// Phase 1, Plan 05 -- search query file (FTS5 MATCH queries).
	//
	// urls_fts and findings_fts are external-content virtual tables; their
	// rowid mirrors the source row's id. The triggers from migration 0001
	// keep them in sync on INSERT/UPDATE/DELETE.
	//
	// SearchFindings is Q5 of the EXPLAIN gate (FTS5 case -- the gate
	// accepts `SCAN findings_fts VIRTUAL TABLE INDEX` and rejects only
	// raw `SCAN findings` on the ordinary table).
	//
	// sqlc parser limitation: it does NOT accept the SQLite-idiomatic
	// `WHERE <virtual_table_name> MATCH ?` form (which searches all
	// indexed columns). It DOES accept a column-qualified MATCH against
	// one of the FTS5 columns, e.g. `WHERE f.path MATCH ?`.
	//
	// Callers wanting a cross-column search supply FTS5 column-selector
	// syntax in the query string itself:
	//    WHERE f.path MATCH ?    args=("path:admin OR title:console")
	// This works because the FTS5 column on the LHS only affects the
	// DEFAULT field; explicit `col:term` tokens in the query string
	// always win. See SQLite FTS5 docs section 3 "Full-text Query Syntax".
	SearchURLs(ctx context.Context, arg SearchURLsParams) ([]SearchURLsRow, error)
	UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error)
	UpdateFindingStatus(ctx context.Context, arg UpdateFindingStatusParams) error
	UpdateHostTriage(ctx context.Context, arg UpdateHostTriageParams) error
	UpdatePortBanner(ctx context.Context, arg UpdatePortBannerParams) error
	UpdateScanCounts(ctx context.Context, arg UpdateScanCountsParams) error
	UpdateScanStatus(ctx context.Context, arg UpdateScanStatusParams) error
	UpdateTarget(ctx context.Context, arg UpdateTargetParams) (Target, error)
	UpdateURLTriage(ctx context.Context, arg UpdateURLTriageParams) error
	// Phase 1, Plan 05 -- companies query file.
	//
	// Caller supplies the ULID `id` (NewCompanyID in the domain layer); the
	// SQL layer never generates IDs. All UPSERT/UPDATE queries return the
	// row via RETURNING * so the caller does not re-fetch.
	//
	// Every query uses `?` or `@named` placeholders (T-Tampering-1 mitigation).
	UpsertCompany(ctx context.Context, arg UpsertCompanyParams) (Company, error)
	// Phase 1, Plan 05 -- findings query file.
	//
	// Natural key uses COALESCE(host_id,0)/COALESCE(port_id,0) to keep
	// NULL-bearing rows comparable; matches idx_findings_dedup.
	//
	// Triage state (status, tags_json, notes) survives re-scan UPSERTs
	// (DAT-03). Severity may be elevated on re-observation (worst-wins),
	// but never demoted.
	//
	// ListFindingsBySeverityForTarget is Q2 of the EXPLAIN gate.
	UpsertFinding(ctx context.Context, arg UpsertFindingParams) (Finding, error)
	UpsertGlobalSetting(ctx context.Context, arg UpsertGlobalSettingParams) (Setting, error)
	// Phase 1, Plan 05 -- hosts query file (canonical asset table).
	//
	// Mirrors RESEARCH Sec5.3 verbatim. UPSERT preserves the canonical-row
	// triage state (status, tags_json, notes) -- the DAT-03 contract. The
	// ON CONFLICT branch only refreshes observation fields and last_seen_at.
	//
	// ListHostsForTarget is Q1 of the EXPLAIN gate; CountHostsForTarget
	// powers paginator UI; UpdateHostTriage is the triage write path.
	UpsertHost(ctx context.Context, arg UpsertHostParams) (Host, error)
	// Phase 1, Plan 05 -- js_files query file.
	//
	// JavaScript artifacts are content-addressed by SHA-256. The UPSERT
	// refreshes last_seen_at and secrets_count when the same JS file is
	// re-observed; tags_json/notes are preserved.
	UpsertJSFile(ctx context.Context, arg UpsertJSFileParams) (JsFile, error)
	// Phase 1, Plan 05 -- ports query file.
	//
	// Natural key is (host_id, port_number, protocol). UPSERT refreshes
	// observation fields (state, service_name, service_version, banner)
	// and last_seen_at; tags_json is preserved across re-scans.
	UpsertPort(ctx context.Context, arg UpsertPortParams) (Port, error)
	UpsertTargetSetting(ctx context.Context, arg UpsertTargetSettingParams) (Setting, error)
	// Phase 1, Plan 05 -- urls query file (canonical asset table).
	//
	// Natural key is the SHA-256 of the canonical URL form (url_hash).
	// UPSERT preserves triage state (status, tags_json, notes) -- the
	// DAT-03 contract -- and only refreshes observation fields.
	//
	// GetURLByHash is Q4 of the EXPLAIN gate.
	UpsertURL(ctx context.Context, arg UpsertURLParams) (URL, error)
}

var _ Querier = (*Queries)(nil)
