// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scan_observation.sql

package sqlcgen

import (
	"context"
)

const diffBetweenScans = `-- name: DiffBetweenScans :many
SELECT scan_observation.asset_kind, scan_observation.asset_id
FROM scan_observation
WHERE scan_observation.target_id = ? AND scan_observation.scan_id = ?
EXCEPT
SELECT scan_observation.asset_kind, scan_observation.asset_id
FROM scan_observation
WHERE scan_observation.target_id = ? AND scan_observation.scan_id = ?
`

type DiffBetweenScansParams struct {
	TargetID   string
	ScanID     string
	TargetID_2 string
	ScanID_2   string
}

type DiffBetweenScansRow struct {
	AssetKind string
	AssetID   int64
}

// Returns rows in scan B that are NOT in scan A, scoped to target T.
// Args (positional): targetIDB, scanB, targetIDA, scanA.
// Both halves use idx_scan_obs_unique (RESEARCH Sec4.2 Q3 expected plan).
// Columns are fully table-qualified to disambiguate the EXCEPT compound
// (sqlc rejects `WHERE target_id = ?` in both halves as "ambiguous").
func (q *Queries) DiffBetweenScans(ctx context.Context, arg DiffBetweenScansParams) ([]DiffBetweenScansRow, error) {
	rows, err := q.db.QueryContext(ctx, diffBetweenScans,
		arg.TargetID,
		arg.ScanID,
		arg.TargetID_2,
		arg.ScanID_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiffBetweenScansRow
	for rows.Next() {
		var i DiffBetweenScansRow
		if err := rows.Scan(&i.AssetKind, &i.AssetID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertObservation = `-- name: InsertObservation :exec

INSERT INTO scan_observation (
    scan_id, target_id, asset_kind, asset_id, observed_at, raw_json
) VALUES (
    ?, ?, ?, ?, ?, ?
)
ON CONFLICT(scan_id, target_id, asset_kind, asset_id) DO NOTHING
`

type InsertObservationParams struct {
	ScanID     string
	TargetID   string
	AssetKind  string
	AssetID    int64
	ObservedAt int64
	RawJson    *string
}

// Phase 1, Plan 05 -- scan_observation query file.
//
// Polymorphic per-scan observation tuple (scan_id, target_id, asset_kind,
// asset_id), unique at the DATABASE level via ux_scan_observation_dedup
// (schema.sql). Until plan 15-18 this comment claimed a uniqueness the DDL
// never provided -- there was no constraint and no index at all, so the "the
// same scan cannot observe the same asset twice" invariant callers relied on
// was enforced nowhere (F10).
//
// The key is FOUR columns, not three: one scan legitimately covers several
// targets, and two targets may observe the same asset id, so target_id is
// part of the identity.
//
// ON CONFLICT DO NOTHING rather than an error: re-observing an asset inside
// one scan is a normal consequence of two artefact lines resolving to the same
// upserted row, and must not turn into a failed ingest.
//
// DiffBetweenScans is Q3 of the EXPLAIN gate.
func (q *Queries) InsertObservation(ctx context.Context, arg InsertObservationParams) error {
	_, err := q.db.ExecContext(ctx, insertObservation,
		arg.ScanID,
		arg.TargetID,
		arg.AssetKind,
		arg.AssetID,
		arg.ObservedAt,
		arg.RawJson,
	)
	return err
}

const listObservationsForAsset = `-- name: ListObservationsForAsset :many
SELECT id, scan_id, target_id, asset_kind, asset_id, observed_at, raw_json FROM scan_observation
WHERE asset_kind = ? AND asset_id = ?
ORDER BY observed_at
`

type ListObservationsForAssetParams struct {
	AssetKind string
	AssetID   int64
}

func (q *Queries) ListObservationsForAsset(ctx context.Context, arg ListObservationsForAssetParams) ([]ScanObservation, error) {
	rows, err := q.db.QueryContext(ctx, listObservationsForAsset, arg.AssetKind, arg.AssetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanObservation
	for rows.Next() {
		var i ScanObservation
		if err := rows.Scan(
			&i.ID,
			&i.ScanID,
			&i.TargetID,
			&i.AssetKind,
			&i.AssetID,
			&i.ObservedAt,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservationsForScan = `-- name: ListObservationsForScan :many
SELECT id, scan_id, target_id, asset_kind, asset_id, observed_at, raw_json FROM scan_observation
WHERE scan_id = ?
ORDER BY observed_at
`

func (q *Queries) ListObservationsForScan(ctx context.Context, scanID string) ([]ScanObservation, error) {
	rows, err := q.db.QueryContext(ctx, listObservationsForScan, scanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanObservation
	for rows.Next() {
		var i ScanObservation
		if err := rows.Scan(
			&i.ID,
			&i.ScanID,
			&i.TargetID,
			&i.AssetKind,
			&i.AssetID,
			&i.ObservedAt,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
