// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scans.sql

package sqlcgen

import (
	"context"
)

const countScansForTarget = `-- name: CountScansForTarget :one
SELECT COUNT(*) FROM scans WHERE target_id = ?
`

func (q *Queries) CountScansForTarget(ctx context.Context, targetID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countScansForTarget, targetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScan = `-- name: CreateScan :one

INSERT INTO scans (
    id, target_id, mode, status, started_at,
    reconftw_version, tool_versions_json,
    raw_args_json, config_overrides_json, output_dir
) VALUES (
    ?1, ?2, ?3, ?4, ?5,
    ?6, ?7,
    ?8, ?9, ?10
)
RETURNING id, target_id, mode, status, started_at, finished_at, exit_code, reconftw_version, tool_versions_json, raw_args_json, config_overrides_json, output_dir, cancelled_by, findings_count, subdomain_count, url_count
`

type CreateScanParams struct {
	ID                  string
	TargetID            string
	Mode                string
	Status              string
	StartedAt           int64
	ReconftwVersion     *string
	ToolVersionsJson    *string
	RawArgsJson         string
	ConfigOverridesJson string
	OutputDir           string
}

// Phase 1, Plan 05 -- scans query file.
//
// Scans are immutable run records. Status transitions go queued ->
// running -> {completed,failed,cancelled,incomplete}. UpdateScanCounts
// is called by Phase 3's OnPhaseEnd at each module boundary.
func (q *Queries) CreateScan(ctx context.Context, arg CreateScanParams) (Scan, error) {
	row := q.db.QueryRowContext(ctx, createScan,
		arg.ID,
		arg.TargetID,
		arg.Mode,
		arg.Status,
		arg.StartedAt,
		arg.ReconftwVersion,
		arg.ToolVersionsJson,
		arg.RawArgsJson,
		arg.ConfigOverridesJson,
		arg.OutputDir,
	)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.TargetID,
		&i.Mode,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExitCode,
		&i.ReconftwVersion,
		&i.ToolVersionsJson,
		&i.RawArgsJson,
		&i.ConfigOverridesJson,
		&i.OutputDir,
		&i.CancelledBy,
		&i.FindingsCount,
		&i.SubdomainCount,
		&i.UrlCount,
	)
	return i, err
}

const diffScansFindings = `-- name: DiffScansFindings :many
SELECT DISTINCT sa.asset_id AS finding_id, f.template_signature, f.severity, f.title
FROM scan_observation sa
JOIN findings f ON f.id = sa.asset_id
WHERE sa.scan_id = ?1
  AND sa.asset_kind = 'finding'
  AND NOT EXISTS (
    SELECT 1 FROM scan_observation sb
    WHERE sb.scan_id = ?2
      AND sb.asset_kind = 'finding'
      AND sb.asset_id = sa.asset_id
  )
ORDER BY sa.asset_id
`

type DiffScansFindingsParams struct {
	ScanA string
	ScanB string
}

type DiffScansFindingsRow struct {
	FindingID         int64
	TemplateSignature string
	Severity          string
	Title             string
}

// Findings diff for ScansDiff handler. asset_kind = 'finding' restricts.
// Returns finding_id + template_signature + severity + title for the
// API DTO.
func (q *Queries) DiffScansFindings(ctx context.Context, arg DiffScansFindingsParams) ([]DiffScansFindingsRow, error) {
	rows, err := q.db.QueryContext(ctx, diffScansFindings, arg.ScanA, arg.ScanB)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiffScansFindingsRow
	for rows.Next() {
		var i DiffScansFindingsRow
		if err := rows.Scan(
			&i.FindingID,
			&i.TemplateSignature,
			&i.Severity,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const diffScansHosts = `-- name: DiffScansHosts :many
SELECT DISTINCT sa.asset_id AS host_id, h.fqdn
FROM scan_observation sa
JOIN hosts h ON h.id = sa.asset_id
WHERE sa.scan_id = ?1
  AND sa.asset_kind = 'host'
  AND NOT EXISTS (
    SELECT 1 FROM scan_observation sb
    WHERE sb.scan_id = ?2
      AND sb.asset_kind = 'host'
      AND sb.asset_id = sa.asset_id
  )
ORDER BY sa.asset_id
`

type DiffScansHostsParams struct {
	ScanA string
	ScanB string
}

type DiffScansHostsRow struct {
	HostID int64
	FQDN   string
}

// Returns host asset_ids that appear in scan_a but not scan_b (or vice
// versa via swap of args). Used by ScansDiff handler -- called twice
// (added: scan_a=to, scan_b=from; removed: scan_a=from, scan_b=to).
// asset_kind = 'host' restricts the polymorphic scan_observation column.
// Returns host_id + fqdn for the API DTO.
func (q *Queries) DiffScansHosts(ctx context.Context, arg DiffScansHostsParams) ([]DiffScansHostsRow, error) {
	rows, err := q.db.QueryContext(ctx, diffScansHosts, arg.ScanA, arg.ScanB)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiffScansHostsRow
	for rows.Next() {
		var i DiffScansHostsRow
		if err := rows.Scan(&i.HostID, &i.FQDN); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const diffScansURLs = `-- name: DiffScansURLs :many
SELECT DISTINCT sa.asset_id AS url_id, u.url
FROM scan_observation sa
JOIN urls u ON u.id = sa.asset_id
WHERE sa.scan_id = ?1
  AND sa.asset_kind = 'url'
  AND NOT EXISTS (
    SELECT 1 FROM scan_observation sb
    WHERE sb.scan_id = ?2
      AND sb.asset_kind = 'url'
      AND sb.asset_id = sa.asset_id
  )
ORDER BY sa.asset_id
`

type DiffScansURLsParams struct {
	ScanA string
	ScanB string
}

type DiffScansURLsRow struct {
	URLID int64
	URL   string
}

// URLs diff for ScansDiff handler. asset_kind = 'url' restricts the
// polymorphic column. Returns url_id + url for the API DTO.
func (q *Queries) DiffScansURLs(ctx context.Context, arg DiffScansURLsParams) ([]DiffScansURLsRow, error) {
	rows, err := q.db.QueryContext(ctx, diffScansURLs, arg.ScanA, arg.ScanB)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiffScansURLsRow
	for rows.Next() {
		var i DiffScansURLsRow
		if err := rows.Scan(&i.URLID, &i.URL); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestCompletedScanForTarget = `-- name: GetLatestCompletedScanForTarget :one
SELECT id, target_id, mode, status, started_at, finished_at, exit_code, reconftw_version, tool_versions_json, raw_args_json, config_overrides_json, output_dir, cancelled_by, findings_count, subdomain_count, url_count FROM scans WHERE target_id = ? AND status = 'completed' ORDER BY started_at DESC LIMIT 1
`

// GetLatestCompletedScanForTarget returns the most recent scan with
// status='completed' for the given target_id, ordered by started_at DESC.
// Returns sql.ErrNoRows when no completed scan exists for the target.
// Phase 10, Plan 01 — Wave 0 blocker for report and monitor diff loop.
func (q *Queries) GetLatestCompletedScanForTarget(ctx context.Context, targetID string) (Scan, error) {
	row := q.db.QueryRowContext(ctx, getLatestCompletedScanForTarget, targetID)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.TargetID,
		&i.Mode,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExitCode,
		&i.ReconftwVersion,
		&i.ToolVersionsJson,
		&i.RawArgsJson,
		&i.ConfigOverridesJson,
		&i.OutputDir,
		&i.CancelledBy,
		&i.FindingsCount,
		&i.SubdomainCount,
		&i.UrlCount,
	)
	return i, err
}

const getScan = `-- name: GetScan :one
SELECT id, target_id, mode, status, started_at, finished_at, exit_code, reconftw_version, tool_versions_json, raw_args_json, config_overrides_json, output_dir, cancelled_by, findings_count, subdomain_count, url_count FROM scans WHERE id = ? LIMIT 1
`

func (q *Queries) GetScan(ctx context.Context, id string) (Scan, error) {
	row := q.db.QueryRowContext(ctx, getScan, id)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.TargetID,
		&i.Mode,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExitCode,
		&i.ReconftwVersion,
		&i.ToolVersionsJson,
		&i.RawArgsJson,
		&i.ConfigOverridesJson,
		&i.OutputDir,
		&i.CancelledBy,
		&i.FindingsCount,
		&i.SubdomainCount,
		&i.UrlCount,
	)
	return i, err
}

const listScansCursor = `-- name: ListScansCursor :many
SELECT id, target_id, mode, status, started_at, finished_at, exit_code, reconftw_version, tool_versions_json, raw_args_json, config_overrides_json, output_dir, cancelled_by, findings_count, subdomain_count, url_count FROM scans
WHERE (CAST(? AS TEXT) = '' OR target_id = ?)
  AND (CAST(? AS TEXT) = '' OR status = ?)
  AND id < ?
ORDER BY id DESC
LIMIT ?
`

type ListScansCursorParams struct {
	Column1  string
	TargetID string
	Column3  string
	Status   string
	ID       string
	Limit    int64
}

// Cursor-based pagination by id DESC, with optional target_id and status
// filters. Caller passes empty string for filters that should match all.
// For the first page, caller passes the ULID-max sentinel (26 'Z' chars)
// as cursor. ULIDs lex-sort. D-16.
func (q *Queries) ListScansCursor(ctx context.Context, arg ListScansCursorParams) ([]Scan, error) {
	rows, err := q.db.QueryContext(ctx, listScansCursor,
		arg.Column1,
		arg.TargetID,
		arg.Column3,
		arg.Status,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scan
	for rows.Next() {
		var i Scan
		if err := rows.Scan(
			&i.ID,
			&i.TargetID,
			&i.Mode,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ExitCode,
			&i.ReconftwVersion,
			&i.ToolVersionsJson,
			&i.RawArgsJson,
			&i.ConfigOverridesJson,
			&i.OutputDir,
			&i.CancelledBy,
			&i.FindingsCount,
			&i.SubdomainCount,
			&i.UrlCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScansForTarget = `-- name: ListScansForTarget :many
SELECT id, target_id, mode, status, started_at, finished_at, exit_code, reconftw_version, tool_versions_json, raw_args_json, config_overrides_json, output_dir, cancelled_by, findings_count, subdomain_count, url_count FROM scans
WHERE target_id = ?
ORDER BY started_at DESC
LIMIT ? OFFSET ?
`

type ListScansForTargetParams struct {
	TargetID string
	Limit    int64
	Offset   int64
}

func (q *Queries) ListScansForTarget(ctx context.Context, arg ListScansForTargetParams) ([]Scan, error) {
	rows, err := q.db.QueryContext(ctx, listScansForTarget, arg.TargetID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scan
	for rows.Next() {
		var i Scan
		if err := rows.Scan(
			&i.ID,
			&i.TargetID,
			&i.Mode,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ExitCode,
			&i.ReconftwVersion,
			&i.ToolVersionsJson,
			&i.RawArgsJson,
			&i.ConfigOverridesJson,
			&i.OutputDir,
			&i.CancelledBy,
			&i.FindingsCount,
			&i.SubdomainCount,
			&i.UrlCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScanCounts = `-- name: UpdateScanCounts :exec
UPDATE scans SET
    findings_count  = ?1,
    subdomain_count = ?2,
    url_count       = ?3
WHERE id = ?4
`

type UpdateScanCountsParams struct {
	FindingsCount  int64
	SubdomainCount int64
	UrlCount       int64
	ID             string
}

func (q *Queries) UpdateScanCounts(ctx context.Context, arg UpdateScanCountsParams) error {
	_, err := q.db.ExecContext(ctx, updateScanCounts,
		arg.FindingsCount,
		arg.SubdomainCount,
		arg.UrlCount,
		arg.ID,
	)
	return err
}

const updateScanStatus = `-- name: UpdateScanStatus :exec
UPDATE scans SET
    status       = ?1,
    finished_at  = ?2,
    exit_code    = ?3,
    cancelled_by = ?4
WHERE id = ?5
`

type UpdateScanStatusParams struct {
	Status      string
	FinishedAt  *int64
	ExitCode    *int64
	CancelledBy *string
	ID          string
}

func (q *Queries) UpdateScanStatus(ctx context.Context, arg UpdateScanStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateScanStatus,
		arg.Status,
		arg.FinishedAt,
		arg.ExitCode,
		arg.CancelledBy,
		arg.ID,
	)
	return err
}
