// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package sqlcgen

import (
	"context"
)

const searchFindings = `-- name: SearchFindings :many
SELECT f.id, f.template_signature, f.severity, f.status, f.title, f.matched_at
FROM findings_fts ff
JOIN findings f ON f.id = ff.rowid
WHERE ff.description MATCH ?1
LIMIT ?2
`

type SearchFindingsParams struct {
	MatchQuery string
	RowLimit   int64
}

type SearchFindingsRow struct {
	ID                int64
	TemplateSignature string
	Severity          string
	Status            string
	Title             string
	MatchedAt         string
}

func (q *Queries) SearchFindings(ctx context.Context, arg SearchFindingsParams) ([]SearchFindingsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchFindings, arg.MatchQuery, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchFindingsRow
	for rows.Next() {
		var i SearchFindingsRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateSignature,
			&i.Severity,
			&i.Status,
			&i.Title,
			&i.MatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchURLs = `-- name: SearchURLs :many

SELECT u.id, u.url, u.title, u.status_code
FROM urls_fts f
JOIN urls u ON u.id = f.rowid
WHERE f.path MATCH ?1
LIMIT ?2
`

type SearchURLsParams struct {
	MatchQuery string
	RowLimit   int64
}

type SearchURLsRow struct {
	ID         int64
	URL        string
	Title      *string
	StatusCode *int64
}

// Phase 1, Plan 05 -- search query file (FTS5 MATCH queries).
//
// urls_fts and findings_fts are external-content virtual tables; their
// rowid mirrors the source row's id. The triggers from migration 0001
// keep them in sync on INSERT/UPDATE/DELETE.
//
// SearchFindings is Q5 of the EXPLAIN gate (FTS5 case -- the gate
// accepts `SCAN findings_fts VIRTUAL TABLE INDEX` and rejects only
// raw `SCAN findings` on the ordinary table).
//
// sqlc parser limitation: it does NOT accept the SQLite-idiomatic
// `WHERE <virtual_table_name> MATCH ?` form (which searches all
// indexed columns). It DOES accept a column-qualified MATCH against
// one of the FTS5 columns, e.g. `WHERE f.path MATCH ?`.
//
// Callers wanting a cross-column search supply FTS5 column-selector
// syntax in the query string itself:
//
//	WHERE f.path MATCH ?    args=("path:admin OR title:console")
//
// This works because the FTS5 column on the LHS only affects the
// DEFAULT field; explicit `col:term` tokens in the query string
// always win. See SQLite FTS5 docs section 3 "Full-text Query Syntax".
func (q *Queries) SearchURLs(ctx context.Context, arg SearchURLsParams) ([]SearchURLsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchURLs, arg.MatchQuery, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchURLsRow
	for rows.Next() {
		var i SearchURLsRow
		if err := rows.Scan(
			&i.ID,
			&i.URL,
			&i.Title,
			&i.StatusCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
