// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlcgen

import (
	"context"
)

const deleteGlobalSetting = `-- name: DeleteGlobalSetting :exec
DELETE FROM settings WHERE scope = 'global' AND key = ?
`

func (q *Queries) DeleteGlobalSetting(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteGlobalSetting, key)
	return err
}

const deleteTargetSetting = `-- name: DeleteTargetSetting :exec
DELETE FROM settings WHERE scope = 'target' AND target_id = ? AND key = ?
`

type DeleteTargetSettingParams struct {
	TargetID *string
	Key      string
}

func (q *Queries) DeleteTargetSetting(ctx context.Context, arg DeleteTargetSettingParams) error {
	_, err := q.db.ExecContext(ctx, deleteTargetSetting, arg.TargetID, arg.Key)
	return err
}

const getGlobalSetting = `-- name: GetGlobalSetting :one

SELECT id, scope, target_id, "key", value_plain, value_encrypted, is_secret, last_test_at, last_test_ok, created_at, updated_at FROM settings
WHERE scope = 'global' AND key = ?
LIMIT 1
`

// Phase 1, Plan 05 -- settings query file.
//
// Two scopes: 'global' and 'target'. Both use partial UNIQUE indexes
// (idx_settings_global, idx_settings_target). Phase 6 will encrypt
// secrets at rest; the T-V6-1 CHECK constraint already prevents
// accidental plaintext when is_secret=1.
func (q *Queries) GetGlobalSetting(ctx context.Context, key string) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getGlobalSetting, key)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.TargetID,
		&i.Key,
		&i.ValuePlain,
		&i.ValueEncrypted,
		&i.IsSecret,
		&i.LastTestAt,
		&i.LastTestOk,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTargetSetting = `-- name: GetTargetSetting :one
SELECT id, scope, target_id, "key", value_plain, value_encrypted, is_secret, last_test_at, last_test_ok, created_at, updated_at FROM settings
WHERE scope = 'target' AND target_id = ? AND key = ?
LIMIT 1
`

type GetTargetSettingParams struct {
	TargetID *string
	Key      string
}

func (q *Queries) GetTargetSetting(ctx context.Context, arg GetTargetSettingParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getTargetSetting, arg.TargetID, arg.Key)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.TargetID,
		&i.Key,
		&i.ValuePlain,
		&i.ValueEncrypted,
		&i.IsSecret,
		&i.LastTestAt,
		&i.LastTestOk,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSettingsForTarget = `-- name: ListSettingsForTarget :many
SELECT id, scope, target_id, "key", value_plain, value_encrypted, is_secret, last_test_at, last_test_ok, created_at, updated_at FROM settings
WHERE scope = 'target' AND target_id = ?
ORDER BY key
`

func (q *Queries) ListSettingsForTarget(ctx context.Context, targetID *string) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, listSettingsForTarget, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setting
	for rows.Next() {
		var i Setting
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.TargetID,
			&i.Key,
			&i.ValuePlain,
			&i.ValueEncrypted,
			&i.IsSecret,
			&i.LastTestAt,
			&i.LastTestOk,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGlobalSetting = `-- name: UpsertGlobalSetting :one
INSERT INTO settings (
    scope, target_id, key, value_plain, value_encrypted, is_secret,
    last_test_at, last_test_ok, created_at, updated_at
) VALUES (
    'global', NULL, ?1, ?2, ?3, ?4,
    ?5, ?6, ?7, ?7
)
ON CONFLICT(key) WHERE scope = 'global' DO UPDATE SET
    value_plain     = excluded.value_plain,
    value_encrypted = excluded.value_encrypted,
    is_secret       = excluded.is_secret,
    last_test_at    = excluded.last_test_at,
    last_test_ok    = excluded.last_test_ok,
    updated_at      = excluded.updated_at
RETURNING id, scope, target_id, "key", value_plain, value_encrypted, is_secret, last_test_at, last_test_ok, created_at, updated_at
`

type UpsertGlobalSettingParams struct {
	Key            string
	ValuePlain     *string
	ValueEncrypted []byte
	IsSecret       int64
	LastTestAt     *int64
	LastTestOk     *int64
	Now            int64
}

func (q *Queries) UpsertGlobalSetting(ctx context.Context, arg UpsertGlobalSettingParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, upsertGlobalSetting,
		arg.Key,
		arg.ValuePlain,
		arg.ValueEncrypted,
		arg.IsSecret,
		arg.LastTestAt,
		arg.LastTestOk,
		arg.Now,
	)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.TargetID,
		&i.Key,
		&i.ValuePlain,
		&i.ValueEncrypted,
		&i.IsSecret,
		&i.LastTestAt,
		&i.LastTestOk,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTargetSetting = `-- name: UpsertTargetSetting :one
INSERT INTO settings (
    scope, target_id, key, value_plain, value_encrypted, is_secret,
    last_test_at, last_test_ok, created_at, updated_at
) VALUES (
    'target', ?1, ?2, ?3, ?4, ?5,
    ?6, ?7, ?8, ?8
)
ON CONFLICT(target_id, key) WHERE scope = 'target' DO UPDATE SET
    value_plain     = excluded.value_plain,
    value_encrypted = excluded.value_encrypted,
    is_secret       = excluded.is_secret,
    last_test_at    = excluded.last_test_at,
    last_test_ok    = excluded.last_test_ok,
    updated_at      = excluded.updated_at
RETURNING id, scope, target_id, "key", value_plain, value_encrypted, is_secret, last_test_at, last_test_ok, created_at, updated_at
`

type UpsertTargetSettingParams struct {
	TargetID       *string
	Key            string
	ValuePlain     *string
	ValueEncrypted []byte
	IsSecret       int64
	LastTestAt     *int64
	LastTestOk     *int64
	Now            int64
}

func (q *Queries) UpsertTargetSetting(ctx context.Context, arg UpsertTargetSettingParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, upsertTargetSetting,
		arg.TargetID,
		arg.Key,
		arg.ValuePlain,
		arg.ValueEncrypted,
		arg.IsSecret,
		arg.LastTestAt,
		arg.LastTestOk,
		arg.Now,
	)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.TargetID,
		&i.Key,
		&i.ValuePlain,
		&i.ValueEncrypted,
		&i.IsSecret,
		&i.LastTestAt,
		&i.LastTestOk,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
