// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: targets.sql

package sqlcgen

import (
	"context"
)

const countTargets = `-- name: CountTargets :one
SELECT COUNT(*) FROM targets
`

func (q *Queries) CountTargets(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTargets)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTarget = `-- name: CreateTarget :one

INSERT INTO targets (
    id, name, description, company_id, recon_dir,
    tags_json, notes, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5,
    ?6, ?7, ?8, ?8
)
RETURNING id, name, description, company_id, recon_dir, tags_json, notes, created_at, updated_at
`

type CreateTargetParams struct {
	ID          string
	Name        string
	Description string
	CompanyID   *string
	ReconDir    string
	TagsJson    string
	Notes       string
	Now         int64
}

// Phase 1, Plan 05 -- targets query file.
//
// The id ULID is supplied by the caller (NewTargetID).
// Engagement-level entity; multiple roots live in `target_roots`.
func (q *Queries) CreateTarget(ctx context.Context, arg CreateTargetParams) (Target, error) {
	row := q.db.QueryRowContext(ctx, createTarget,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CompanyID,
		arg.ReconDir,
		arg.TagsJson,
		arg.Notes,
		arg.Now,
	)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CompanyID,
		&i.ReconDir,
		&i.TagsJson,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTarget = `-- name: DeleteTarget :exec
DELETE FROM targets WHERE id = ?
`

func (q *Queries) DeleteTarget(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTarget, id)
	return err
}

const getTarget = `-- name: GetTarget :one
SELECT id, name, description, company_id, recon_dir, tags_json, notes, created_at, updated_at FROM targets WHERE id = ? LIMIT 1
`

func (q *Queries) GetTarget(ctx context.Context, id string) (Target, error) {
	row := q.db.QueryRowContext(ctx, getTarget, id)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CompanyID,
		&i.ReconDir,
		&i.TagsJson,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTargetByName = `-- name: GetTargetByName :one
SELECT id, name, description, company_id, recon_dir, tags_json, notes, created_at, updated_at FROM targets WHERE name = ? LIMIT 1
`

func (q *Queries) GetTargetByName(ctx context.Context, name string) (Target, error) {
	row := q.db.QueryRowContext(ctx, getTargetByName, name)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CompanyID,
		&i.ReconDir,
		&i.TagsJson,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTargets = `-- name: ListTargets :many
SELECT id, name, description, company_id, recon_dir, tags_json, notes, created_at, updated_at FROM targets
ORDER BY name
LIMIT ? OFFSET ?
`

type ListTargetsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListTargets(ctx context.Context, arg ListTargetsParams) ([]Target, error) {
	rows, err := q.db.QueryContext(ctx, listTargets, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Target
	for rows.Next() {
		var i Target
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CompanyID,
			&i.ReconDir,
			&i.TagsJson,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargetsByCompany = `-- name: ListTargetsByCompany :many
SELECT id, name, description, company_id, recon_dir, tags_json, notes, created_at, updated_at FROM targets
WHERE company_id = ?
ORDER BY name
LIMIT ? OFFSET ?
`

type ListTargetsByCompanyParams struct {
	CompanyID *string
	Limit     int64
	Offset    int64
}

func (q *Queries) ListTargetsByCompany(ctx context.Context, arg ListTargetsByCompanyParams) ([]Target, error) {
	rows, err := q.db.QueryContext(ctx, listTargetsByCompany, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Target
	for rows.Next() {
		var i Target
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CompanyID,
			&i.ReconDir,
			&i.TagsJson,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargetsCursor = `-- name: ListTargetsCursor :many
SELECT id, name, description, company_id, recon_dir, tags_json, notes, created_at, updated_at FROM targets
WHERE id < ?
ORDER BY id DESC
LIMIT ?
`

type ListTargetsCursorParams struct {
	ID    string
	Limit int64
}

// Cursor-based pagination by id DESC. Caller passes the last_id from the
// previous page; for the first page, caller passes a ULID-max-sentinel
// ('ZZZZZZZZZZZZZZZZZZZZZZZZZZ' -- 26 'Z's, greater than every real ULID
// in Crockford base32). ULIDs are lexicographically sortable so the
// PRIMARY KEY index on targets.id satisfies ORDER BY id DESC. D-16.
func (q *Queries) ListTargetsCursor(ctx context.Context, arg ListTargetsCursorParams) ([]Target, error) {
	rows, err := q.db.QueryContext(ctx, listTargetsCursor, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Target
	for rows.Next() {
		var i Target
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CompanyID,
			&i.ReconDir,
			&i.TagsJson,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTargetReconDir = `-- name: UpdateTargetReconDir :exec
UPDATE targets SET
    recon_dir  = ?1,
    updated_at = ?2
WHERE id = ?3
`

type UpdateTargetReconDirParams struct {
	ReconDir string
	Now      int64
	ID       string
}

// Plan 15-18 -- repoint an existing target at its current workspace.
//
// ensureTarget only writes recon_dir when it CREATES the target, so a target
// scanned again with a different --output kept pointing at the first run's
// directory forever, and every reader that resolves artefacts through
// targets.recon_dir read a stale tree. It is also what repairs the recon_dir
// values left behind by the workspace rename in plan 15-01.
func (q *Queries) UpdateTargetReconDir(ctx context.Context, arg UpdateTargetReconDirParams) error {
	_, err := q.db.ExecContext(ctx, updateTargetReconDir, arg.ReconDir, arg.Now, arg.ID)
	return err
}

const updateTarget = `-- name: UpdateTarget :one
UPDATE targets SET
    name        = ?1,
    description = ?2,
    company_id  = ?3,
    recon_dir   = ?4,
    tags_json   = ?5,
    notes       = ?6,
    updated_at  = ?7
WHERE id = ?8
RETURNING id, name, description, company_id, recon_dir, tags_json, notes, created_at, updated_at
`

type UpdateTargetParams struct {
	Name        string
	Description string
	CompanyID   *string
	ReconDir    string
	TagsJson    string
	Notes       string
	Now         int64
	ID          string
}

func (q *Queries) UpdateTarget(ctx context.Context, arg UpdateTargetParams) (Target, error) {
	row := q.db.QueryRowContext(ctx, updateTarget,
		arg.Name,
		arg.Description,
		arg.CompanyID,
		arg.ReconDir,
		arg.TagsJson,
		arg.Notes,
		arg.Now,
		arg.ID,
	)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CompanyID,
		&i.ReconDir,
		&i.TagsJson,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
