// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: target_roots.sql

package sqlcgen

import (
	"context"
)

const deleteTargetRoot = `-- name: DeleteTargetRoot :exec
DELETE FROM target_roots WHERE id = ?
`

func (q *Queries) DeleteTargetRoot(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTargetRoot, id)
	return err
}

const insertTargetRoot = `-- name: InsertTargetRoot :one

INSERT INTO target_roots (
    target_id, root_value, root_type, scope_kind, created_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5
)
RETURNING id, target_id, root_value, root_type, scope_kind, created_at
`

type InsertTargetRootParams struct {
	TargetID  string
	RootValue string
	RootType  string
	ScopeKind string
	Now       int64
}

// Phase 1, Plan 05 -- target_roots query file.
//
// Each target has 1..N roots; scope_kind=include defines the in-scope
// root set; scope_kind=exclude carves holes (Phase 3 ingest gates each
// row through scope.ApplyExclusions which consults these queries).
//
// Phase 3 will call ListIncludeRoots+ListExcludeRoots once per scan
// on the writer pool to seed its in-memory scope cache.
func (q *Queries) InsertTargetRoot(ctx context.Context, arg InsertTargetRootParams) (TargetRoot, error) {
	row := q.db.QueryRowContext(ctx, insertTargetRoot,
		arg.TargetID,
		arg.RootValue,
		arg.RootType,
		arg.ScopeKind,
		arg.Now,
	)
	var i TargetRoot
	err := row.Scan(
		&i.ID,
		&i.TargetID,
		&i.RootValue,
		&i.RootType,
		&i.ScopeKind,
		&i.CreatedAt,
	)
	return i, err
}

const listExcludeRoots = `-- name: ListExcludeRoots :many
SELECT id, target_id, root_value, root_type, scope_kind, created_at FROM target_roots
WHERE target_id = ? AND scope_kind = 'exclude'
ORDER BY created_at
`

func (q *Queries) ListExcludeRoots(ctx context.Context, targetID string) ([]TargetRoot, error) {
	rows, err := q.db.QueryContext(ctx, listExcludeRoots, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TargetRoot
	for rows.Next() {
		var i TargetRoot
		if err := rows.Scan(
			&i.ID,
			&i.TargetID,
			&i.RootValue,
			&i.RootType,
			&i.ScopeKind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncludeRoots = `-- name: ListIncludeRoots :many
SELECT id, target_id, root_value, root_type, scope_kind, created_at FROM target_roots
WHERE target_id = ? AND scope_kind = 'include'
ORDER BY created_at
`

func (q *Queries) ListIncludeRoots(ctx context.Context, targetID string) ([]TargetRoot, error) {
	rows, err := q.db.QueryContext(ctx, listIncludeRoots, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TargetRoot
	for rows.Next() {
		var i TargetRoot
		if err := rows.Scan(
			&i.ID,
			&i.TargetID,
			&i.RootValue,
			&i.RootType,
			&i.ScopeKind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargetRoots = `-- name: ListTargetRoots :many
SELECT id, target_id, root_value, root_type, scope_kind, created_at FROM target_roots
WHERE target_id = ?
ORDER BY created_at
`

func (q *Queries) ListTargetRoots(ctx context.Context, targetID string) ([]TargetRoot, error) {
	rows, err := q.db.QueryContext(ctx, listTargetRoots, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TargetRoot
	for rows.Next() {
		var i TargetRoot
		if err := rows.Scan(
			&i.ID,
			&i.TargetID,
			&i.RootValue,
			&i.RootType,
			&i.ScopeKind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
