// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: urls.sql

package sqlcgen

import (
	"context"
)

const attachURLToTarget = `-- name: AttachURLToTarget :exec
INSERT INTO target_url(target_id, url_id) VALUES (?, ?)
ON CONFLICT(target_id, url_id) DO NOTHING
`

type AttachURLToTargetParams struct {
	TargetID string
	URLID    int64
}

func (q *Queries) AttachURLToTarget(ctx context.Context, arg AttachURLToTargetParams) error {
	_, err := q.db.ExecContext(ctx, attachURLToTarget, arg.TargetID, arg.URLID)
	return err
}

const getURL = `-- name: GetURL :one
SELECT id, url, url_hash, scheme, host_id, port, path, query_canonical, status_code, content_type, content_length, title, tech_json, screenshot_path, first_seen_at, last_seen_at, status, tags_json, notes, raw_json FROM urls WHERE id = ? LIMIT 1
`

func (q *Queries) GetURL(ctx context.Context, id int64) (URL, error) {
	row := q.db.QueryRowContext(ctx, getURL, id)
	var i URL
	err := row.Scan(
		&i.ID,
		&i.URL,
		&i.UrlHash,
		&i.Scheme,
		&i.HostID,
		&i.Port,
		&i.Path,
		&i.QueryCanonical,
		&i.StatusCode,
		&i.ContentType,
		&i.ContentLength,
		&i.Title,
		&i.TechJson,
		&i.ScreenshotPath,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Status,
		&i.TagsJson,
		&i.Notes,
		&i.RawJson,
	)
	return i, err
}

const getURLByHash = `-- name: GetURLByHash :one
SELECT id, url, url_hash, scheme, host_id, port, path, query_canonical, status_code, content_type, content_length, title, tech_json, screenshot_path, first_seen_at, last_seen_at, status, tags_json, notes, raw_json FROM urls WHERE url_hash = ? LIMIT 1
`

func (q *Queries) GetURLByHash(ctx context.Context, urlHash []byte) (URL, error) {
	row := q.db.QueryRowContext(ctx, getURLByHash, urlHash)
	var i URL
	err := row.Scan(
		&i.ID,
		&i.URL,
		&i.UrlHash,
		&i.Scheme,
		&i.HostID,
		&i.Port,
		&i.Path,
		&i.QueryCanonical,
		&i.StatusCode,
		&i.ContentType,
		&i.ContentLength,
		&i.Title,
		&i.TechJson,
		&i.ScreenshotPath,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Status,
		&i.TagsJson,
		&i.Notes,
		&i.RawJson,
	)
	return i, err
}

const listURLsCursor = `-- name: ListURLsCursor :many
SELECT u.id, u.url, u.url_hash, u.scheme, u.host_id, u.port,
       u.path, u.query_canonical, u.status_code, u.content_type,
       u.content_length, u.title, u.tech_json, u.screenshot_path,
       u.first_seen_at, u.last_seen_at, u.status, u.tags_json,
       u.notes, u.raw_json
FROM urls u
WHERE (?1 = 0 OR u.host_id = ?1)
  AND (?2 = 0 OR u.status_code = ?2)
  AND (?3 = '' OR u.content_type = ?3)
  AND (?4 = 0 OR
       u.last_seen_at < ?4 OR
       (u.last_seen_at = ?4 AND u.id < ?5))
ORDER BY u.last_seen_at DESC, u.id DESC
LIMIT ?6
`

type ListURLsCursorParams struct {
	HostIDFilter      interface{}
	StatusCodeFilter  interface{}
	ContentTypeFilter interface{}
	CursorSeenAt      interface{}
	CursorLastID      int64
	RowLimit          int64
}

// Plan 04-04 - cursor-paginated URL list for GET /api/v1/urls.
//
// Filter columns: host_id (0 disables), status_code (0 disables), content_type ("" disables).
// Cursor: composite (last_seen_at, id) - Disc-02 for non-ULID canonical
// assets. SQLite >= 3.15 supports tuple comparison but sqlc parses the
// explicit form more reliably.
func (q *Queries) ListURLsCursor(ctx context.Context, arg ListURLsCursorParams) ([]URL, error) {
	rows, err := q.db.QueryContext(ctx, listURLsCursor,
		arg.HostIDFilter,
		arg.StatusCodeFilter,
		arg.ContentTypeFilter,
		arg.CursorSeenAt,
		arg.CursorLastID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []URL
	for rows.Next() {
		var i URL
		if err := rows.Scan(
			&i.ID,
			&i.URL,
			&i.UrlHash,
			&i.Scheme,
			&i.HostID,
			&i.Port,
			&i.Path,
			&i.QueryCanonical,
			&i.StatusCode,
			&i.ContentType,
			&i.ContentLength,
			&i.Title,
			&i.TechJson,
			&i.ScreenshotPath,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.Status,
			&i.TagsJson,
			&i.Notes,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listURLsCursorByHost = `-- name: ListURLsCursorByHost :many
SELECT u.id, u.url, u.url_hash, u.scheme, u.host_id, u.port,
       u.path, u.query_canonical, u.status_code, u.content_type,
       u.content_length, u.title, u.tech_json, u.screenshot_path,
       u.first_seen_at, u.last_seen_at, u.status, u.tags_json,
       u.notes, u.raw_json
FROM urls u
WHERE u.screenshot_path IS NOT NULL AND u.screenshot_path <> ''
  AND (?1 = 0 OR u.host_id = ?1)
  AND (?2 = 0 OR
       u.last_seen_at < ?2 OR
       (u.last_seen_at = ?2 AND u.id < ?3))
ORDER BY u.last_seen_at DESC, u.id DESC
LIMIT ?4
`

type ListURLsCursorByHostParams struct {
	HostIDFilter interface{}
	CursorSeenAt interface{}
	CursorLastID int64
	RowLimit     int64
}

// Variant used by the screenshots handler - lists URLs that have a
// non-empty screenshot_path, filtered by host_id. Reuses the urls table
// because the v1 schema does not split screenshots into a dedicated
// table (screenshot_path is a URL column).
func (q *Queries) ListURLsCursorByHost(ctx context.Context, arg ListURLsCursorByHostParams) ([]URL, error) {
	rows, err := q.db.QueryContext(ctx, listURLsCursorByHost,
		arg.HostIDFilter,
		arg.CursorSeenAt,
		arg.CursorLastID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []URL
	for rows.Next() {
		var i URL
		if err := rows.Scan(
			&i.ID,
			&i.URL,
			&i.UrlHash,
			&i.Scheme,
			&i.HostID,
			&i.Port,
			&i.Path,
			&i.QueryCanonical,
			&i.StatusCode,
			&i.ContentType,
			&i.ContentLength,
			&i.Title,
			&i.TechJson,
			&i.ScreenshotPath,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.Status,
			&i.TagsJson,
			&i.Notes,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listURLsForHost = `-- name: ListURLsForHost :many
SELECT id, url, url_hash, scheme, host_id, port, path, query_canonical, status_code, content_type, content_length, title, tech_json, screenshot_path, first_seen_at, last_seen_at, status, tags_json, notes, raw_json FROM urls
WHERE host_id = ?
ORDER BY path
LIMIT ? OFFSET ?
`

type ListURLsForHostParams struct {
	HostID *int64
	Limit  int64
	Offset int64
}

func (q *Queries) ListURLsForHost(ctx context.Context, arg ListURLsForHostParams) ([]URL, error) {
	rows, err := q.db.QueryContext(ctx, listURLsForHost, arg.HostID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []URL
	for rows.Next() {
		var i URL
		if err := rows.Scan(
			&i.ID,
			&i.URL,
			&i.UrlHash,
			&i.Scheme,
			&i.HostID,
			&i.Port,
			&i.Path,
			&i.QueryCanonical,
			&i.StatusCode,
			&i.ContentType,
			&i.ContentLength,
			&i.Title,
			&i.TechJson,
			&i.ScreenshotPath,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.Status,
			&i.TagsJson,
			&i.Notes,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listURLsForScan = `-- name: ListURLsForScan :many
SELECT u.id, u.url, u.url_hash, u.scheme, u.host_id, u.port, u.path, u.query_canonical, u.status_code, u.content_type, u.content_length, u.title, u.tech_json, u.screenshot_path, u.first_seen_at, u.last_seen_at, u.status, u.tags_json, u.notes, u.raw_json
FROM scan_observation so
JOIN urls u ON u.id = so.asset_id
WHERE so.scan_id = ? AND so.asset_kind = 'url'
ORDER BY u.id
LIMIT ? OFFSET ?
`

type ListURLsForScanParams struct {
	ScanID string
	Limit  int64
	Offset int64
}

// Plan 15-18 -- the URLs ONE scan observed, paginated. Same column list as
// ListURLsForTarget; only the scoping differs.
func (q *Queries) ListURLsForScan(ctx context.Context, arg ListURLsForScanParams) ([]URL, error) {
	rows, err := q.db.QueryContext(ctx, listURLsForScan, arg.ScanID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []URL
	for rows.Next() {
		var i URL
		if err := rows.Scan(
			&i.ID,
			&i.URL,
			&i.UrlHash,
			&i.Scheme,
			&i.HostID,
			&i.Port,
			&i.Path,
			&i.QueryCanonical,
			&i.StatusCode,
			&i.ContentType,
			&i.ContentLength,
			&i.Title,
			&i.TechJson,
			&i.ScreenshotPath,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.Status,
			&i.TagsJson,
			&i.Notes,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listURLsForTarget = `-- name: ListURLsForTarget :many
SELECT u.id, u.url, u.url_hash, u.scheme, u.host_id, u.port, u.path, u.query_canonical, u.status_code, u.content_type, u.content_length, u.title, u.tech_json, u.screenshot_path, u.first_seen_at, u.last_seen_at, u.status, u.tags_json, u.notes, u.raw_json
FROM target_url tu
JOIN urls u ON u.id = tu.url_id
WHERE tu.target_id = ?
ORDER BY u.url
LIMIT ? OFFSET ?
`

type ListURLsForTargetParams struct {
	TargetID string
	Limit    int64
	Offset   int64
}

func (q *Queries) ListURLsForTarget(ctx context.Context, arg ListURLsForTargetParams) ([]URL, error) {
	rows, err := q.db.QueryContext(ctx, listURLsForTarget, arg.TargetID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []URL
	for rows.Next() {
		var i URL
		if err := rows.Scan(
			&i.ID,
			&i.URL,
			&i.UrlHash,
			&i.Scheme,
			&i.HostID,
			&i.Port,
			&i.Path,
			&i.QueryCanonical,
			&i.StatusCode,
			&i.ContentType,
			&i.ContentLength,
			&i.Title,
			&i.TechJson,
			&i.ScreenshotPath,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.Status,
			&i.TagsJson,
			&i.Notes,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchURLTags = `-- name: PatchURLTags :one
UPDATE urls
SET tags_json = ?1
WHERE id = ?2
RETURNING id, url, url_hash, scheme, host_id, port, path, query_canonical, status_code, content_type, content_length, title, tech_json, screenshot_path, first_seen_at, last_seen_at, status, tags_json, notes, raw_json
`

type PatchURLTagsParams struct {
	NewTagsJson string
	ID          int64
}

// Plan 04-04 - single-URL tag patch (POST /api/v1/urls/bulk loop body).
// Atomic per-row update inside WithWriteTx; soft-atomicity surfaced via
// per-id errors[] in handler response.
func (q *Queries) PatchURLTags(ctx context.Context, arg PatchURLTagsParams) (URL, error) {
	row := q.db.QueryRowContext(ctx, patchURLTags, arg.NewTagsJson, arg.ID)
	var i URL
	err := row.Scan(
		&i.ID,
		&i.URL,
		&i.UrlHash,
		&i.Scheme,
		&i.HostID,
		&i.Port,
		&i.Path,
		&i.QueryCanonical,
		&i.StatusCode,
		&i.ContentType,
		&i.ContentLength,
		&i.Title,
		&i.TechJson,
		&i.ScreenshotPath,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Status,
		&i.TagsJson,
		&i.Notes,
		&i.RawJson,
	)
	return i, err
}

const updateURLTriage = `-- name: UpdateURLTriage :exec
UPDATE urls SET
    status    = ?1,
    tags_json = ?2,
    notes     = ?3
WHERE id = ?4
`

type UpdateURLTriageParams struct {
	Status   string
	TagsJson string
	Notes    string
	ID       int64
}

func (q *Queries) UpdateURLTriage(ctx context.Context, arg UpdateURLTriageParams) error {
	_, err := q.db.ExecContext(ctx, updateURLTriage,
		arg.Status,
		arg.TagsJson,
		arg.Notes,
		arg.ID,
	)
	return err
}

const upsertURL = `-- name: UpsertURL :one

INSERT INTO urls (
    url, url_hash, scheme, host_id, port,
    path, query_canonical, status_code,
    content_type, content_length, title, tech_json,
    screenshot_path, first_seen_at, last_seen_at,
    status, tags_json, notes, raw_json
) VALUES (
    ?1, ?2, ?3, ?4, ?5,
    ?6, ?7, ?8,
    ?9, ?10, ?11, ?12,
    ?13, ?14, ?14,
    'new', '[]', '', ?15
)
ON CONFLICT(url_hash) DO UPDATE SET
    last_seen_at    = excluded.last_seen_at,
    status_code     = COALESCE(excluded.status_code, urls.status_code),
    content_type    = COALESCE(excluded.content_type, urls.content_type),
    content_length  = COALESCE(excluded.content_length, urls.content_length),
    title           = COALESCE(excluded.title, urls.title),
    tech_json       = COALESCE(excluded.tech_json, urls.tech_json),
    screenshot_path = COALESCE(excluded.screenshot_path, urls.screenshot_path),
    raw_json        = COALESCE(excluded.raw_json, urls.raw_json)
RETURNING id, url, url_hash, scheme, host_id, port, path, query_canonical, status_code, content_type, content_length, title, tech_json, screenshot_path, first_seen_at, last_seen_at, status, tags_json, notes, raw_json
`

type UpsertURLParams struct {
	URL            string
	UrlHash        []byte
	Scheme         string
	HostID         *int64
	Port           *int64
	Path           string
	QueryCanonical string
	StatusCode     *int64
	ContentType    *string
	ContentLength  *int64
	Title          *string
	TechJson       *string
	ScreenshotPath *string
	Now            int64
	RawJson        *string
}

// Phase 1, Plan 05 -- urls query file (canonical asset table).
//
// Natural key is the SHA-256 of the canonical URL form (url_hash).
// UPSERT preserves triage state (status, tags_json, notes) -- the
// DAT-03 contract -- and only refreshes observation fields.
//
// GetURLByHash is Q4 of the EXPLAIN gate.
func (q *Queries) UpsertURL(ctx context.Context, arg UpsertURLParams) (URL, error) {
	row := q.db.QueryRowContext(ctx, upsertURL,
		arg.URL,
		arg.UrlHash,
		arg.Scheme,
		arg.HostID,
		arg.Port,
		arg.Path,
		arg.QueryCanonical,
		arg.StatusCode,
		arg.ContentType,
		arg.ContentLength,
		arg.Title,
		arg.TechJson,
		arg.ScreenshotPath,
		arg.Now,
		arg.RawJson,
	)
	var i URL
	err := row.Scan(
		&i.ID,
		&i.URL,
		&i.UrlHash,
		&i.Scheme,
		&i.HostID,
		&i.Port,
		&i.Path,
		&i.QueryCanonical,
		&i.StatusCode,
		&i.ContentType,
		&i.ContentLength,
		&i.Title,
		&i.TechJson,
		&i.ScreenshotPath,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Status,
		&i.TagsJson,
		&i.Notes,
		&i.RawJson,
	)
	return i, err
}
