# Generated by Django 4.0.5 on 2022-11-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0005_remove_subtakeover_takeover_subtakeover_subdomain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudassets',
            name='azure',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cloudassets',
            name='google',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cloudassets',
            name='appfound',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cloudassets',
            name='protected_s3bucket',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
