# Generated by Django 4.0.5 on 2022-11-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0006_cloudassets_azure_cloudassets_google_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webfullinfouncommon',
            name='webfullinfouncommon',
        ),
        migrations.AddField(
            model_name='webfullinfouncommon',
            name='ip',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='webfullinfouncommon',
            name='port',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='webfullinfouncommon',
            name='tech',
            field=models.CharField(blank=True, default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='webfullinfouncommon',
            name='url',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
    ]
