# Generated by Django 4.0.5 on 2022-12-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0007_remove_webfullinfouncommon_webfullinfouncommon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshots',
            name='port',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
