# Generated by Django 4.0.5 on 2022-12-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0008_screenshots_port'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portscanactive',
            old_name='address',
            new_name='ip',
        ),
        migrations.RemoveField(
            model_name='portscanactive',
            name='extraports',
        ),
        migrations.AddField(
            model_name='portscanactive',
            name='status',
            field=models.CharField(blank=True, default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='portscanactive',
            name='hostname',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
    ]
