# Generated by Django 4.1.4 on 2022-12-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0009_rename_address_portscanactive_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomainsdns',
            name='a_record',
            field=models.CharField(blank=True, default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='subdomainsdns',
            name='aaaa_record',
            field=models.CharField(blank=True, default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='subdomainsdns',
            name='cname',
            field=models.CharField(blank=True, default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='subdomainsdns',
            name='host',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subdomainsdns',
            name='internal_ips_record',
            field=models.CharField(blank=True, default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='subdomainsdns',
            name='mx_record',
            field=models.CharField(blank=True, default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='subdomainsdns',
            name='ns_record',
            field=models.CharField(blank=True, default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='subdomainsdns',
            name='resolver',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subdomainsdns',
            name='soa_record',
            field=models.CharField(blank=True, default='N/A', max_length=200),
        ),
    ]
