# Generated by Django 4.1.4 on 2022-12-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0010_alter_subdomainsdns_a_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webfullinfo',
            name='a',
            field=models.CharField(blank=True, default='N/A', max_length=700),
        ),
        migrations.AlterField(
            model_name='webfullinfo',
            name='technologies',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
