# Generated by Django 4.1.4 on 2022-12-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0011_alter_webfullinfo_a_alter_webfullinfo_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webfullinfo',
            name='port',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='webfullinfo',
            name='url',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
